// API type definitions (hand-written supplements)
//
// Phase 6.4: The canonical types are auto-generated by ts-rs in
// `src/generated/`.  This file contains hand-written types that either
// (a) extend generated types with UI-only fields, (b) are not yet
// generated, or (c) are legacy types pending migration.
//
// Re-export generated types that were previously duplicated here (6-10).
// Consumers importing from `types/api` still work; new code should import
// from `generated/` directly.
import type { ToolCallInfo } from '../generated';
export type { ChatRequest, ChatResponse, ToolCallInfo, ContextStats, SessionInfo } from '../generated';
// covered by ts-rs, or (c) represent frontend-only state.  When adding
// or changing a type, prefer updating the Rust-side serde derives and
// re-generating over hand-writing here.
//
// Bridge: `src/generated/index.ts` re-exports all generated types.
// Hand-written supplements should import from `../generated` and export
// their extensions, so consumers can `import { X } from '../types/api'`
// without knowing whether X is generated or hand-written.
//
// Known gaps (types NOT yet generated):
//   - ChatRunStatus (enum with frontend-only states like 'connecting')
//   - ApprovalRequest / InputRequest / SelectionRequest (extend generated)
//   - ExecutionRound (frontend-specific aggregation)
// These should be migrated to generated types as the Rust models stabilize.

// NOTE (6-10): The following types have identical generated counterparts and
// are imported from ../generated instead of being duplicated here:
//   ChatRequest, ChatResponse, ToolCallInfo, ContextStats, SessionInfo.
// See `generated/` for the canonical definitions.

export type ChatRunStatus =
  | 'idle'
  | 'running'
  | 'thinking'
  | 'using_tool'
  | 'waiting_approval'
  | 'waiting_input'
  | 'completed'
  | 'failed'
  | 'cancelled';

export interface ToolInfo {
  name: string;
  description: string;
  source: string;
  input_schema?: Record<string, unknown>;
  enabled: boolean;
}

export interface SkillInfo {
  name: string;
  description: string;
  file: string;
  loaded?: boolean;
  source?: string;
  triggers?: string[];
  tags?: string[];
  version?: string | null;
  author?: string | null;
  has_sandbox?: boolean;
  depends_on?: string[];
  // Superpowers deep integration fields
  category?: string;
  is_baseline?: boolean;
  is_builtin?: boolean;
  upstream_version?: string | null;
  has_updates?: boolean;
  missing_dependencies?: string[];
}

/** Category display names (i18n). */
export const CATEGORY_LABELS: Record<string, string> = {
  methodology: '方法论',
  development: '开发',
  document: '文档',
  design: '设计',
  research: '研究',
  automation: '自动化',
};

export interface McpServerInfo {
  name: string;
  status: 'connected' | 'disconnected' | 'error' | 'disabled';
  transport: string;
  tool_count?: number;
  tools?: McpToolInfo[];
  connected_at?: string | null;
  error?: string | null;
  enabled?: boolean;
}

export interface McpToolInfo {
  name: string;
  description: string;
  input_schema?: Record<string, unknown>;
}

export interface ConnectMcpRequest {
  name: string;
  transport: McpTransportConfig;
}

export type McpTransportConfig =
  | { stdio: { command: string; args?: string[]; env?: Record<string, string> } }
  | { http: { url: string; headers?: Record<string, string> } }
  | { sse: { url: string; headers?: Record<string, string> } };

export interface MemoryEntry {
  namespace: string;
  key: string;
  value: any; // serde_json::Value can be any JSON value
  created_at: number;
  updated_at: number;
  score?: number; // optional relevance score for search results
}

export interface NamespacesResponse {
  namespaces: string[][]; // Vec<Vec<String>> in Rust
}

export interface SnapshotInfo {
  id: string;
  iteration: number;
  created_at: number;
}

export interface PermissionRule {
  name: string;
  tool_pattern: string;
  effect: 'allow' | 'deny' | 'ask';
  priority: number;
}

export interface AuditLog {
  id: string;
  timestamp: string;
  tool_name: string;
  args: unknown;
  decision: string;
  reason?: string;
}

export interface WorkflowInfo {
  id: string;
  name: string;
  definition: string;
  status: string;
  created_at: string;
}

export interface ConfigInfo {
  model: string;
  system_prompt: string;
  max_iterations: number;
  max_tokens: number;
  enable_tools: boolean;
  enable_memory: boolean;
  enable_human_in_loop: boolean;
}

// ── 附件类型 ──

export interface Attachment {
  name: string;
  mime_type: string;
  data: string; // base64 encoded
  size: number;
}

// Execution round: one ReAct loop iteration (think → tools)
export interface ExecutionRound {
  /** Thinking that precedes this round's tools */
  thinking?: { content: string };
  /** Tools executed in this round (parallel if >1) */
  tools: ToolCallInfo[];
}

// Chat store types
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  thinkingContent?: string; // deprecated, kept for history display
  thinkingSegments?: { content: string }[];
  attachments?: { name: string; mime_type: string; url: string; size: number }[];
  toolCalls?: ToolCallInfo[];
  chartSpecs?: unknown[];
  isStreaming?: boolean;
  timestamp: number;
  /** @deprecated Use executionRounds instead. Flat execution order tracking for backward compat. */
  executionSteps?: { type: 'thinking' | 'tool'; index: number }[];
  /** Execution rounds: each round = one ReAct iteration (thinking + tool batch) */
  executionRounds?: ExecutionRound[];
}

export interface ApprovalRequest {
  requestId: string;
  toolName: string;
  args: unknown;
  prompt?: string;
}

// History types (matching backend MessageItem)
export interface HistoryMessage {
  role: string;
  content: string | null;
  tool_calls?: HistoryToolCall[];
}

export interface HistoryToolCall {
  id: string;
  name: string;
  arguments: string;
}

export interface HistoryResponse {
  messages: HistoryMessage[];
  total: number;
}

// Snapshot metadata for localStorage cache
export interface SnapshotMeta {
  title: string;
  preview: string;
  messageCount: number;
  createdAt: number;
}

// ── Compression types ──

export interface CompressionStats {
  current_tokens: number;
  token_limit: number;
  message_count: number;
  compression_ratio: number;
  needs_compression: boolean;
}

export interface CompressResponse {
  success: boolean;
  messages_before: number;
  messages_after: number;
  tokens_saved: number;
  message: string;
}

// ── Extract types ──

export interface ExtractRequest {
  input: string;
  schema: object;
  schema_name?: string;
}

export interface ExtractResponse {
  success: boolean;
  data: unknown;
  schema_name: string;
}

export interface ValidateSchemaResponse {
  valid: boolean;
  errors: string[];
}

export interface ExtractExample {
  name: string;
  description: string;
  schema: object;
  example_input: string;
}

// ── Conversation persistence types ──

export interface SavedMessage {
  role: string;
  content: string | null;
  tool_calls?: { id: string; name: string; arguments: string }[];
  thinking_segments?: string[];
  execution_steps?: { type: string; index: number }[];
  execution_rounds?: {
    thinking?: { content: string };
    tools: { name: string; args: unknown; result: string; success: boolean }[];
  }[];
  tool_result?: string | null;
  /** User-uploaded attachments (images/documents) as data URLs, so the
   * message renders identically after reload. */
  attachments?: { name: string; mime_type: string; url: string; size: number }[];
}

export interface ConversationRecord {
  id: string;
  conversation_id: string;
  title: string;
  messages: SavedMessage[];
  created_at: string;
  updated_at: string;
}

export interface ConversationListItem {
  id: number;
  conversation_id: string;
  title: string | null;
  message_count: number;
  created_at: string;
  updated_at: string;
}

// ── Sandbox types ──

export interface SandboxStatus {
  local_available: boolean;
  docker_available: boolean;
  k8s_available: boolean;
  current_backend: string;
}

export interface SandboxConfig {
  security_level: 'low' | 'medium' | 'high';
  max_memory_mb: number | null;
  max_cpu_seconds: number | null;
  network_enabled: boolean;
}

export interface SandboxExecuteRequest {
  language: string;
  code: string;
}

export interface SandboxExecuteResult {
  success: boolean;
  stdout: string;
  stderr: string;
  exit_code: number | null;
  duration_ms: number;
}

// ── Context info ── (reuses ContextStats)

// ── Full Config types ──

export interface FullConfigResponse {
  model: {
    provider: string;
    name: string;
    has_auth_token: boolean;
    base_url: string | null;
    max_tokens: number | null;
    temperature: number | null;
  };
  agent: {
    model: string;
    system_prompt: string;
    max_iterations: number;
    token_limit: number;
    enable_tools: boolean;
    enable_memory: boolean;
    enable_human_loop: boolean;
    session_id: string | null;
    available_models: string[];
  };
  mcp: { config_path: string | null };
  channels: {
    qq: { enabled: boolean; app_id: string };
    feishu: { enabled: boolean; app_id: string; mode: string };
    session: {
      timeout_minutes: number;
      reset_keywords: string[];
      reset_commands: string[];
    };
  };
  server: { host: string; port: number };
  logging: { level: string };
}

export interface FullConfigUpdateRequest {
  model?: {
    max_tokens?: number;
    temperature?: number;
  };
  agent?: {
    name?: string;
    system_prompt?: string;
    max_iterations?: number;
    enable_tools?: boolean;
    enable_memory?: boolean;
    enable_human_in_loop?: boolean;
    memory_path?: string;
  };
  mcp?: { config_path?: string };
  channels?: {
    qq?: { enabled?: boolean; app_id?: string; client_secret?: string };
    feishu?: { enabled?: boolean; app_id?: string; app_secret?: string; mode?: string };
    session?: {
      timeout_minutes?: number;
      reset_keywords?: string[];
      reset_commands?: string[];
    };
  };
  server?: { host?: string; port?: number };
  logging?: { level?: string };
}

// ── MCP 配置类型 ──

export interface McpConfig {
  mcpServers: Record<string, McpServerEntry>;
}

export interface McpServerEntry {
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  url?: string;
  headers?: Record<string, string>;
  transport?: string;
  disabled?: boolean;
}

// ── 认证相关类型 ──

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  token_type: string;
  expires_in: number;
}

export interface AuthState {
  isAuthenticated: boolean;
  token: string | null;
  tokenType: string | null;
  expiresAt: number | null;
  isLoading: boolean;
  error: string | null;
}

export interface HealthResponse {
  status: string;
  timestamp: string;
}

// ── Evolution / 自进化 types ──

export interface ShareGPTMessage {
  from: string;
  value: string;
}

export interface TrajectoryEntry {
  id: string;
  session_id: string;
  conversations: ShareGPTMessage[];
  model: string;
  completed: boolean;
  timestamp: string;
  token_usage: number;
  tool_call_count: number;
  duration_ms: number;
}

export interface TrajectoryStats {
  total: number;
  completed: number;
  failed: number;
  total_tokens: number;
  total_tool_calls: number;
  avg_duration_ms: number;
}

// Renamed from ReviewOutcome (6-10 C-tier): the generated `ReviewOutcome` is
// the task-review enum ("pass"|"needs_fix"|"blocked"), which collided with
// this evolution-specific struct. Disambiguated as TrajectoryReviewOutcome.
export interface TrajectoryReviewOutcome {
  run_id: string;
  actions: string[];
  nothing_to_save: boolean;
  error?: string | null;
}

export interface CuratorStatus {
  total: number;
  active: number;
  stale: number;
  archived: number;
  pinned: number;
  last_run_at: string | null;
}

export interface CuratorTransition {
  skill: string;
  from: string;
  to: string;
}

// ── Provider types ──────────────────────────────────────────────────────────

export interface ProviderTemplate {
  id: string;
  name: string;
  base_url: string;
  api_key_env: string;
  default_models: string[];
  requires_api_key: boolean;
}

export interface ConfiguredModel {
  id: string;
  display_name: string;
  provider: string;
  model: string;
  enabled: boolean;
  is_default: boolean;
  has_auth_token: boolean;
  auth_source: 'config' | 'env' | 'none' | string;
  base_url: string | null;
  temperature: number | null;
  max_tokens: number | null;
  context_window: number | null;
}

export interface ConfiguredModelListResponse {
  models: ConfiguredModel[];
  default_model_id: string | null;
}

export interface TestConnectionResponse {
  success: boolean;
  response?: string;
  error?: string;
  model?: string;
  auth_source?: 'input' | 'config' | 'env' | 'none' | string;
  has_auth_token?: boolean;
}
