// API type definitions (hand-written supplements)
//
// Phase 6.4: The canonical types are auto-generated by ts-rs in
// `src/generated/`.  This file contains hand-written types that either
// (a) extend generated types with UI-only fields, (b) are not yet
// generated, or (c) are legacy types pending migration.
//
// Re-export generated types that were previously duplicated here (6-10).
// Consumers importing from `types/api` still work; new code should import
// from `generated/` directly.
export type {
  ChatRequest,
  ChatResponse,
  ToolCallInfo,
  ContextStats,
  SessionInfo,
  ToolInfo,
  ConversationInputAddress,
  ConversationInputAttempt,
  ConversationInputFact,
  ConversationInputFrontier,
  ConversationInputIdentity,
  ConversationInputOutcome,
  ConversationInputPayload,
  ConversationInputPhase,
  ConversationInputProjection,
  ConversationInputReceipt,
  ConversationInputSource,
} from '../generated';
import type {
  BackgroundCellState,
  ConversationInputFact,
  ExtensionSkillEntry,
  McpServerInfo as GeneratedMcpServerInfo,
  McpToolInfo as GeneratedMcpToolInfo,
} from '../generated';
// covered by ts-rs, or (c) represent frontend-only state.  When adding
// or changing a type, prefer updating the Rust-side serde derives and
// re-generating over hand-writing here.
//
// Bridge: `src/generated/index.ts` re-exports all generated types.
// Hand-written supplements should import from `../generated` and export
// their extensions, so consumers can `import { X } from '../types/api'`
// without knowing whether X is generated or hand-written.
//
// Known gaps (types NOT yet generated):
//   - ChatRunStatus (enum with frontend-only states like 'connecting')
//   - ApprovalRequest / InputRequest / SelectionRequest (extend generated)
//   - ExecutionRound (frontend-specific aggregation)
// These should be migrated to generated types as the Rust models stabilize.

// NOTE (6-10): The following types have identical generated counterparts and
// are imported from ../generated instead of being duplicated here:
//   ChatRequest, ChatResponse, ToolCallInfo, ContextStats, SessionInfo.
// See `generated/` for the canonical definitions.

export type ChatRunStatus =
  | 'idle'
  | 'running'
  | 'thinking'
  | 'using_tool'
  | 'waiting_approval'
  | 'waiting_input'
  | 'completed'
  | 'failed'
  | 'cancelled';

export type ToolExecutionStatus =
  'running' | 'succeeded' | 'failed' | 'cancelled' | 'timed_out' | 'interrupted' | 'unknown';

export type ToolExecutionOwner =
  { kind: 'chat'; message_id: string } | { kind: 'subagent'; subagent_run_id: string };

export type ToolFailureCategory =
  | 'invalid_arguments'
  | 'unavailable'
  | 'timeout'
  | 'cancelled'
  | 'transient'
  | 'permanent'
  | 'partial_side_effect';

export type ToolRecoveryAction =
  'correct_arguments' | 'retry' | 'restore_then_retry' | 'verify_then_retry' | 'stop';

export interface ToolFailure {
  category: ToolFailureCategory;
  recovery: ToolRecoveryAction;
  side_effect: 'none' | 'possible' | 'confirmed';
  retry_after_ms?: number;
  idempotency_key?: string;
  postcondition?: string;
}

export type ToolInvocationRewrite =
  'intervention_redirect' | 'intervention_arguments' | 'pre_tool_use_hook' | 'approval';

export interface ToolInvocation {
  requested_name: string;
  requested_args: unknown;
  name: string;
  args: unknown;
  rewrites?: ToolInvocationRewrite[];
}

export type ToolResultKind =
  | { kind_type: 'text' }
  | { kind_type: 'json' }
  | { kind_type: 'image'; mime_type: string }
  | { kind_type: 'table'; columns: string[]; rows: string[][] }
  | { kind_type: 'diff'; unified_diff: string }
  | { kind_type: 'file_reference'; path: string }
  | { kind_type: 'command_output'; exit_code?: number | null }
  | { kind_type: 'skill_activation'; name: string }
  | { kind_type: 'structured_error'; error_code: string };

export interface ToolResult {
  kind: ToolResultKind;
  success: boolean;
  output: string;
  error?: string | null;
  failure?: ToolFailure | null;
  data?: unknown | null;
  truncated: boolean;
  mime_type?: string | null;
  metadata: Record<string, string>;
}

export interface ToolExecution {
  id: string;
  call_id: string;
  owner: ToolExecutionOwner;
  workspace_id: string;
  conversation_id?: string | null;
  run_id?: string | null;
  name: string;
  args_preview: string;
  status: ToolExecutionStatus;
  started_at: number;
  finished_at?: number | null;
  duration_ms?: number | null;
  detail_ref: string;
}

export interface ToolExecutionDetailManifest {
  id: string;
  invocation: ToolInvocation;
  status: ToolExecutionStatus;
  result?: ToolResult | null;
  output_bytes: number;
}

export type ToolExecutionDetailChannel = 'stdout' | 'stderr' | 'log' | 'result';

export interface ToolExecutionDetailChunk {
  channel: ToolExecutionDetailChannel;
  text: string;
}

export interface ToolExecutionDetailPage {
  chunks: ToolExecutionDetailChunk[];
  next_cursor?: string | null;
  complete: boolean;
}

/**
 * ChatEvent — 后端推给前端的聊天事件 (P2-5 discriminated union)。
 *
 * 此前定义在 useTauriChat.ts 且未导出, chatEventHandler 只好用宽接口
 * ChatEventLike + 调用方 `as any` 强转, 失去编译期类型安全。提取为公共类型,
 * 让 handleChatEvent 直接接收 ChatEvent, 每种 type 的 payload 字段精确可查。
 */
export type ChatEvent = {
  message_key?: string;
  conversation_id?: string | null;
} & (
  | { type: 'token'; data: string }
  | { type: 'thinking_start' }
  | { type: 'thinking_end'; prompt_tokens: number; completion_tokens: number }
  | {
      type: 'llm_usage';
      model: string;
      prompt_tokens: number;
      completion_tokens: number;
      total_tokens: number;
      cached_prompt_tokens: number;
      cache_creation_prompt_tokens: number;
      usage_reported: boolean;
    }
  | {
      type: 'context_compressed';
      before_count: number;
      after_count: number;
      before_tokens: number;
      after_tokens: number;
    }
  | { type: 'chart'; spec: unknown }
  | { type: 'final_answer'; data: string }
  | { type: 'cancelled' }
  | { type: 'error'; message: string }
  | { type: 'run_status'; status: ChatRunStatus }
  | { type: 'notice'; level: 'info' | 'warning' | 'error' | string; code: string; message: string }
  | { type: 'execution_path'; observed_path: string }
  | {
      type: 'approval_request';
      request_id: string;
      tool_name: string;
      args: unknown;
      prompt: string;
    }
  | { type: 'input_request'; request_id: string; prompt: string }
  | {
      type: 'selection_request';
      request_id: string;
      prompt: string;
      options: string[];
      task_id?: string | null;
      context?: unknown;
      phase?: string | null;
    }
  | { type: 'tool_batch_start'; tool_count: number }
  | { type: 'tool_batch_end' }
  | { type: 'interrupt_prompt'; run_id: string; goal: string; new_message: string }
);

export type AgentFailureCategory =
  | 'llm'
  | 'tool'
  | 'parse'
  | 'agent'
  | 'config'
  | 'mcp'
  | 'memory'
  | 'sandbox'
  | 'runtime_state'
  | 'channel'
  | 'io'
  | 'other';

export type AgentTerminalKind = 'failed' | 'cancelled' | 'timed_out' | 'permission_denied';

export interface AgentFailure {
  category: AgentFailureCategory;
  terminal_kind: AgentTerminalKind;
  retryable: boolean;
  code: string;
  http_status: number | null;
  message: string;
}

export type ToolStreamEvent =
  | { event_type: 'progress'; message: string; percent: number | null }
  | { event_type: 'output'; channel: 'stdout' | 'stderr' | 'log'; chunk: string }
  | ({ event_type: 'complete' } & ToolResult);

export type AgentEvent =
  | { type: 'token'; data: string }
  | { type: 'think_start' }
  | { type: 'think_end'; data: { prompt_tokens: number; completion_tokens: number } }
  | {
      type: 'llm_usage';
      data: {
        model: string;
        prompt_tokens: number;
        completion_tokens: number;
        total_tokens: number;
        cached_prompt_tokens: number;
        cache_creation_prompt_tokens: number;
        usage_reported: boolean;
      };
    }
  | { type: 'budget_decision'; data: Record<string, unknown> }
  | { type: 'tool_call'; data: { call_id: string; invocation: ToolInvocation } }
  | {
      type: 'tool_stream';
      data: { call_id: string; name: string; event: ToolStreamEvent };
    }
  | { type: 'tool_result'; data: { call_id: string; name: string; result: ToolResult } }
  | { type: 'tool_batch_start'; data: { tool_count: number } }
  | { type: 'tool_batch_end' }
  | { type: 'guard_triggered'; data: { guard: string; blocked: boolean } }
  | { type: 'memory_recalled'; data: { count: number } }
  | {
      type: 'context_compressed';
      data: {
        before_count: number;
        after_count: number;
        before_tokens: number;
        after_tokens: number;
      };
    }
  | { type: 'chart'; data: { spec: unknown } }
  | { type: 'error'; data: { source: string; message: string; failure: AgentFailure } }
  | { type: 'safety_notice'; data: Record<string, unknown> }
  | { type: 'parameter_error'; data: Record<string, unknown> }
  | { type: 'final_answer'; data: string }
  | { type: 'cancelled' };

export interface AgentEventEnvelope {
  schema_version: number;
  event_id: string;
  content_hash: string;
  sequence: number;
  stream_id: string;
  conversation_id: string | null;
  run_id: string | null;
  turn_id: string;
  message_id: string | null;
  execution_id: string | null;
  parent_event_id: string | null;
  timestamp: string;
  payload: AgentEvent;
}

export type ChatDriverEvent =
  | { source: 'agent'; event: AgentEventEnvelope }
  | { source: 'execution'; event: Record<string, unknown> }
  | { source: 'turn_status'; event: { status: ChatRunStatus } }
  | { source: 'execution_path'; event: { observed_path: string } }
  | { source: 'interrupt'; event: { run_id: string; goal: string; new_message: string } }
  | { source: 'input_lifecycle'; event: ConversationInputFact }
  | {
      source: 'approval_request';
      event: { request_id: string; tool_name: string; args: unknown; prompt: string };
    }
  | { source: 'input_request'; event: { request_id: string; prompt: string } }
  | {
      source: 'selection_request';
      event: {
        request_id: string;
        prompt: string;
        options: string[];
        task_id: string | null;
        context: unknown;
        phase: string | null;
      };
    }
  | {
      source: 'context_compressed';
      event: {
        before_count: number;
        after_count: number;
        before_tokens: number;
        after_tokens: number;
      };
    }
  | { source: 'command_cell_started'; event: { cell: BackgroundCellState } }
  | { source: 'command_cell_settled'; event: { cell: BackgroundCellState } }
  | { source: 'command_cell_watch_ready'; event: { result: CommandCellWatchResult } }
  | {
      source: 'command_cell_watch_delivery_started';
      event: { acknowledgement: CommandCellWatchAcknowledgement };
    }
  | {
      source: 'command_cell_watch_acknowledged';
      event: { acknowledgement: CommandCellWatchAcknowledgement };
    };

export interface CommandCellWatchReceipt {
  execution_id: string;
  watch_generation: number;
  cell_id: string;
  workspace_id: string;
  conversation_id: string;
  run_id: string | null;
  root_turn_id: string;
  state: 'started' | 'settled' | 'cancelled' | 'failed';
  started_at: string;
  settled_at: string | null;
}

export interface CommandCellWatchResult {
  receipt: CommandCellWatchReceipt;
  cell: BackgroundCellState;
}

export interface CommandCellWatchAcknowledgement {
  execution_id: string;
  watch_generation: number;
  cell_id: string;
  workspace_id: string;
  conversation_id: string;
  root_turn_id: string;
  acknowledged_turn_id: string;
  outcome: 'drained' | 'outcome_unknown';
}

export interface ChatEventEnvelope {
  schema_version: number;
  workspace_id: string;
  event_id: string;
  content_hash: string;
  sequence: number;
  stream_id: string;
  conversation_id: string | null;
  root_turn_id: string;
  turn_id: string;
  message_id: string;
  timestamp: string;
  payload: ChatDriverEvent;
}

export interface ChatEventReplay {
  events: ChatEventEnvelope[];
  retained_earliest_cursor: number | null;
  returned_earliest_cursor: number | null;
  latest_cursor: number;
  truncated: boolean;
}

/** Product DTO emitted directly by the application extension authority. */
export type TauriSkillInfo = ExtensionSkillEntry;

export type SkillUpdateState =
  'up_to_date' | 'update_available' | 'local_changes' | 'untracked' | 'error';

export interface SkillUpdateStatus {
  name: string;
  state: SkillUpdateState;
  current_revision?: string | null;
  remote_revision?: string | null;
  message: string;
}

/** Category display names (i18n). */
export const CATEGORY_LABELS: Record<string, string> = {
  methodology: '方法论',
  development: '开发',
  document: '文档',
  design: '设计',
  research: '研究',
  automation: '自动化',
};

/** MCP tool projection emitted by the Tauri MCP commands. */
export type TauriMcpToolInfo = Pick<GeneratedMcpToolInfo, 'name' | 'description'> &
  Partial<Pick<GeneratedMcpToolInfo, 'input_schema'>>;

/** Product projection emitted by the Tauri MCP commands. */
export type TauriMcpServerInfo = Pick<
  GeneratedMcpServerInfo,
  'name' | 'transport' | 'connected_at' | 'error'
> & {
  status: 'connected' | 'disconnected' | 'error' | 'disabled';
  tool_count?: number;
  tools?: TauriMcpToolInfo[];
  enabled?: boolean;
};

export interface MemoryEntry {
  namespace: string;
  key: string;
  value: any; // serde_json::Value can be any JSON value
  created_at: number;
  updated_at: number;
  score?: number; // optional relevance score for search results
}

export interface MemoryProjectionSettlementReceipt {
  authority_scope: string;
  workspace_generation: string;
  revision: string;
  changed: boolean;
  status: 'settled' | 'degraded';
  primary_bound: boolean;
  pool_bound: boolean;
  future_bound: boolean;
  pending_revision: string | null;
  error: string | null;
}

export interface ReflectionReceipt {
  authority_scope: string;
  workspace_generation: string;
  workspace_id: string;
  conversation_id: string | null;
  key: string;
  content_summary: string;
  content_chars: number;
  projection: MemoryProjectionSettlementReceipt;
}

export interface NamespacesResponse {
  namespaces: string[][]; // Vec<Vec<String>> in Rust
}

export interface SnapshotInfo {
  id: string;
  iteration: number;
  created_at: number;
}

export type PermissionRuleMatcher =
  | { type: 'tool'; name: string }
  | { type: 'pattern'; pattern: string }
  | { type: 'permission'; permission: 'Read' | 'Write' | 'Network' | 'Execute' | 'Sensitive' }
  | { type: 'all' };

export type PermissionRuleBehavior =
  { type: 'allow' } | { type: 'deny'; reason: string } | { type: 'ask'; suggestions: string[] };

export type PermissionRuleSource =
  | 'default'
  | 'localsettings'
  | 'projectsettings'
  | 'usersettings'
  | 'managed'
  | 'cliarg'
  | 'session';

export interface PermissionRule {
  matcher: PermissionRuleMatcher;
  behavior: PermissionRuleBehavior;
  source: PermissionRuleSource;
  description?: string | null;
}

export interface PermissionRuleInput {
  matcher: string;
  behavior: 'allow' | 'deny' | 'ask';
  source?: string;
}

export interface AuditLog {
  id: string;
  timestamp: string;
  tool_name: string;
  args: unknown;
  decision: string;
  reason?: string;
}

export interface ConfigInfo {
  model: string;
  system_prompt: string;
  max_iterations: number;
  max_tokens: number;
  enable_tools: boolean;
  enable_memory: boolean;
  enable_human_in_loop: boolean;
}

// ── 附件类型 ──

export interface Attachment {
  name: string;
  mime_type: string;
  data: string; // base64 encoded
  size: number;
  source?: 'upload' | 'paste' | 'channel' | 'message';
}

// Execution round: one ReAct loop iteration (think → tools)
export interface ExecutionRound {
  /** Thinking that precedes this round's tools */
  thinking?: { content: string };
  /** Stable call IDs executed in this round (parallel if >1). */
  toolCallIds: string[];
}

export type ExecutionStep = { type: 'thinking'; index: number } | { type: 'tool'; callId: string };

// Chat store types
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  thinkingContent?: string; // deprecated, kept for history display
  thinkingSegments?: { content: string }[];
  attachments?: {
    name: string;
    mime_type: string;
    url: string;
    size: number;
    source?: Attachment['source'];
  }[];
  chartSpecs?: unknown[];
  isStreaming?: boolean;
  timestamp: number;
  /** @deprecated Use executionRounds instead. Flat execution order tracking for backward compat. */
  executionSteps?: ExecutionStep[];
  /** Execution rounds: each round = one ReAct iteration (thinking + tool batch) */
  executionRounds?: ExecutionRound[];
}

export interface ApprovalRequest {
  requestId: string;
  toolName: string;
  args: unknown;
  prompt?: string;
}

// History types (matching backend MessageItem)
// Snapshot metadata for localStorage cache
export interface SnapshotMeta {
  title: string;
  preview: string;
  messageCount: number;
  createdAt: number;
}

// ── Compression types ──

export interface CompressionStats {
  current_tokens: number;
  token_limit: number;
  message_count: number;
  compression_ratio: number;
  protected_message_count?: number;
  runtime_recovery_active?: boolean;
  needs_compression: boolean;
}

export interface CompressResponse {
  success: boolean;
  messages_before: number;
  messages_after: number;
  tokens_saved: number;
  message: string;
}

// ── Conversation persistence types ──

export interface SavedMessage {
  message_id?: string;
  role: string;
  content: string | null;
  tool_calls?: { id: string; name: string; arguments: string }[];
  thinking_segments?: string[];
  execution_steps?: { type: string; index?: number; call_id?: string }[];
  execution_rounds?: {
    thinking?: { content: string };
    tool_call_ids: string[];
  }[];
  tool_result?: string | null;
  /** Inline attachments retain their data URL. Artifact-backed text keeps
   * metadata only, so it can render after reload without duplicating content. */
  attachments?: {
    name: string;
    mime_type: string;
    url: string;
    size: number;
    source?: Attachment['source'];
  }[];
}

export interface ConversationRecord {
  id: string;
  conversation_id: string;
  title: string;
  messages: SavedMessage[];
  created_at: string;
  updated_at: string;
}

export interface ConversationListItem {
  id: number;
  conversation_id: string;
  title: string | null;
  message_count: number;
  created_at: string;
  updated_at: string;
}

// ── Sandbox types ──

export interface SandboxStatus {
  local_available: boolean;
  docker_available: boolean;
  k8s_available: boolean;
  current_backend: string;
}

export interface SandboxConfig {
  security_level: 'low' | 'medium' | 'high';
  max_memory_mb: number | null;
  max_cpu_seconds: number | null;
  network_enabled: boolean;
}

export interface SandboxExecuteRequest {
  language: string;
  code: string;
}

export interface SandboxExecuteResult {
  success: boolean;
  stdout: string;
  stderr: string;
  exit_code: number | null;
  duration_ms: number;
  sandbox_type: string;
  timed_out: boolean;
}

// ── Context info ── (reuses ContextStats)

// ── Full Config types ──

export interface FullConfigResponse {
  model: {
    provider: string;
    name: string;
    has_auth_token: boolean;
    base_url: string | null;
    max_tokens: number | null;
    temperature: number | null;
  };
  agent: {
    model: string;
    system_prompt: string;
    max_iterations: number;
    token_limit: number;
    enable_tools: boolean;
    enable_memory: boolean;
    enable_human_loop: boolean;
    session_id: string | null;
    available_models: string[];
  };
  mcp: { config_path: string | null };
  channels: {
    qq: { enabled: boolean; app_id: string };
    feishu: { enabled: boolean; app_id: string; mode: string };
    session: {
      timeout_minutes: number;
      reset_keywords: string[];
      reset_commands: string[];
    };
  };
  server: { host: string; port: number };
  logging: { level: string };
}

export interface FullConfigUpdateRequest {
  model?: {
    max_tokens?: number;
    temperature?: number;
  };
  agent?: {
    name?: string;
    system_prompt?: string;
    max_iterations?: number;
    enable_tools?: boolean;
    enable_memory?: boolean;
    enable_human_in_loop?: boolean;
    memory_path?: string;
  };
  mcp?: { config_path?: string };
  channels?: {
    qq?: { enabled?: boolean; app_id?: string; client_secret?: string };
    feishu?: { enabled?: boolean; app_id?: string; app_secret?: string; mode?: string };
    session?: {
      timeout_minutes?: number;
      reset_keywords?: string[];
      reset_commands?: string[];
    };
  };
  server?: { host?: string; port?: number };
  logging?: { level?: string };
}

// ── MCP 配置类型 ──

export interface McpConfig {
  mcpServers: Record<string, McpServerEntry>;
}

export interface McpServerEntry {
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  url?: string;
  headers?: Record<string, string>;
  transport?: string;
  disabled?: boolean;
}

// ── 认证相关类型 ──

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  token_type: string;
  expires_in: number;
}

export interface AuthState {
  isAuthenticated: boolean;
  token: string | null;
  tokenType: string | null;
  expiresAt: number | null;
  isLoading: boolean;
  error: string | null;
}

export interface HealthResponse {
  status: string;
  timestamp: string;
}

// ── Evolution / 自进化 types ──

export interface CuratorStatus {
  total: number;
  active: number;
  stale: number;
  archived: number;
  pinned: number;
  last_run_at: string | null;
}

export interface CuratorTransition {
  skill: string;
  from: string;
  to: string;
}

// ── Evolution Dashboard types (镜像 app-core DashboardMetrics) ──────────────

export interface MemoryStats {
  count: number;
  avg_confidence: number;
  active_count: number;
  archived_count: number;
}

export interface ToolFailurePattern {
  tool_name: string;
  error_class: string;
  pattern: string;
  input_shape: string;
  occurrence_count: number;
  distinct_run_count: number;
  run_ids: string[];
  ineffective_retry_count: number;
  first_seen: string | null;
  last_seen: string | null;
}

export interface ToolDiagnostics {
  repeated_failures: ToolFailurePattern[];
  scan_error: string | null;
}

export interface ActivityEntry {
  activity_type: string;
  description: string;
  timestamp: string;
}

export interface DashboardMetrics {
  /** key = MemoryType 字符串(UserPreference/ProjectFact/...),后端 HashMap 序列化 */
  memory_by_type: Record<string, MemoryStats>;
  /** key = MemoryStatus 字符串(Active/Archived/...) */
  memory_by_status: Record<string, number>;
  total_memories: number;
  tool_diagnostics: ToolDiagnostics;
  recent_activities: ActivityEntry[];
  generated_at: string;
}

/** 规则晋升候选(镜像 app-core RuleProposal)。用户在 EvolutionPanel 审阅后采纳。 */
export interface RuleProposal {
  memory_key: string;
  namespace: string[];
  rule_text: string;
  confidence: number;
  memory_type: string;
  proposed_at: string;
  reason: string;
}

/** 技能候选(SkillCandidateDetector 从重复模式/调试经验中检测出)。 */
export interface SkillCandidateInfo {
  name: string;
  description: string;
  sample_count: number;
  source_type: string;
  has_draft: boolean;
  activated: boolean;
  confidence: number;
}

export type EvidenceCandidateStatus = 'pending' | 'applied' | 'rejected';
export type EvidenceInboxFilter = 'pending' | 'expired' | 'applied';
export type EvidenceKind =
  | 'user_preference'
  | 'project_fact'
  | 'debugging_lesson'
  | 'error_resolution'
  | 'workflow_pattern'
  | 'skill'
  | 'memory_conflict';

export interface EvidenceRef {
  source: 'background_reviewer' | 'trigger_detector' | 'auto_memory' | 'memory_reviewer';
  source_run_id?: string;
  source_role?: string;
  source_turn?: number;
  source_memory_key?: string;
  quote: string;
}

export interface MemoryConflictMember {
  key: string;
  content: string;
  confidence: number;
  status: 'draft' | 'active' | 'superseded' | 'archived';
  recall_count: number;
  updated_at: number;
}

export interface MemoryConflictProposal {
  topic: string;
  memory_type: string;
  recommended_primary_key: string;
  members: MemoryConflictMember[];
}

export type EvidenceAction =
  { kind: 'save_memory' } | { kind: 'merge_memories'; proposal: MemoryConflictProposal };

export type EvidenceTarget =
  | { kind: 'memory'; key: string }
  | {
      kind: 'memory_merge';
      primary_key: string;
      superseded_keys: string[];
      before: Array<{ key: string; content: string; meta: unknown }>;
    };

export interface EvidenceCandidate {
  schema_version: number;
  candidate_id: string;
  fingerprint: string;
  kind: EvidenceKind;
  scope: { kind: 'user' | 'workspace' | 'session'; id: string };
  content: string;
  evidence: EvidenceRef[];
  action: EvidenceAction;
  confidence: number;
  status: EvidenceCandidateStatus;
  target?: EvidenceTarget;
  revision: number;
  created_at: string;
  updated_at: string;
  expired?: boolean;
}

export interface TestConnectionResponse {
  success: boolean;
  response?: string;
  error?: string;
  model?: string;
  auth_source?: 'input' | 'config' | 'env' | 'none' | string;
  has_auth_token?: boolean;
}
