import { get, post, put, del } from './client';
import { isTauri, apiInvoke } from '../lib/tauri-bridge';
// A-tier types that have identical generated counterparts — import from
// generated to eliminate the same-name duplication (6-10).
import type { SessionInfo, ContextStats, ToolInfo } from '../generated';
import type {
  TauriSkillInfo,
  SkillSyncResult,
  SkillUpdateStatus,
  TauriMcpServerInfo,
  McpConfig,
  MemoryEntry,
  NamespacesResponse,
  SnapshotInfo,
  ConfigInfo,
  PermissionRule,
  AuditLog,
  WorkflowInfo,
  SandboxStatus,
  SandboxConfig,
  SandboxExecuteRequest,
  SandboxExecuteResult,
  CompressResponse,
  CompressionStats,
  ExtractResponse,
  ValidateSchemaResponse,
  ExtractExample,
  ConversationListItem,
  ConversationRecord,
  SavedMessage,
  FullConfigResponse,
  FullConfigUpdateRequest,
  CuratorStatus,
  CuratorTransition,
  DashboardMetrics,
  RuleProposal,
  SkillCandidateInfo,
  EvidenceCandidate,
  EvidenceInboxFilter,
  ConfiguredModelListResponse,
  ProviderTemplate,
  TestConnectionResponse,
  ToolExecution,
  ToolExecutionDetailManifest,
  ToolExecutionDetailPage,
} from '../types/api';
// TaskRuntime types (generated by ts-rs; barrel-exported from ../generated).
import type {
  TaskRun,
  TaskPlan,
  TaskUpdateRequest,
  TodoItem,
  RuntimeTaskEvent,
  RuntimeArtifact,
  ReviewResult,
  TaskExecutionSummary,
  RecoveryBlocker,
} from '../generated';

type LoadSkillsResponse = {
  success: boolean;
  loaded?: string[];
  count?: number;
  skills?: TauriSkillInfo[];
};

export interface AutoMemoryObservation {
  category: 'Project' | 'User' | 'Bug' | 'Decision' | 'FilePath';
  text: string;
  confidence: number;
  source_turn?: number;
}

export interface AutoMemoryStatus {
  enabled: boolean;
  observation_count: number;
  config: {
    enabled: boolean;
    min_confidence: number;
    max_per_session: number;
    categories: string[];
  };
  memory_path?: string;
}

export interface AutoMemoryPreview {
  observations: AutoMemoryObservation[];
  count: number;
  formatted: string;
}

export interface AutoMemoryExtractResult extends AutoMemoryPreview {
  success: boolean;
  memory_path?: string;
  message?: string;
  queued?: number;
  candidates?: EvidenceCandidate[];
}

export const sessionApi = {
  get: () => (isTauri() ? apiInvoke<SessionInfo>('get_session') : get<SessionInfo>('/session')),
  reset: () =>
    isTauri() ? apiInvoke<SessionInfo>('reset_session') : post<SessionInfo>('/session/reset'),
  getLatest: () =>
    isTauri()
      ? apiInvoke<{
          found: boolean;
          id?: string;
          title?: string;
          updated_at?: string;
          message_count?: number;
          error?: string;
        }>('get_latest_session')
      : get<{
          found: boolean;
          id?: string;
          title?: string;
          updated_at?: string;
          message_count?: number;
          error?: string;
        }>('/session/latest'),

  createCheckpoint: () =>
    isTauri()
      ? apiInvoke<{ success: boolean; snapshot_id?: string }>('create_checkpoint')
      : post<{ success: boolean; snapshot_id?: string }>('/session/checkpoint'),
  listCheckpoints: () =>
    isTauri()
      ? apiInvoke<SnapshotInfo[]>('list_checkpoints')
      : get<SnapshotInfo[]>('/session/checkpoints'),
  restoreCheckpoint: (id: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; restored_to?: string }>('restore_checkpoint', {
          snapshot_id: id,
        })
      : post<{ success: boolean; restored_to?: string }>(`/session/restore/${id}`),
};

export const toolsApi = {
  list: () => (isTauri() ? apiInvoke<ToolInfo[]>('list_tools') : get<ToolInfo[]>('/tools')),
  get: (name: string) =>
    isTauri() ? apiInvoke<ToolInfo>('get_tool', { name }) : get<ToolInfo>(`/tools/${name}`),
  enable: (name: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('enable_tool', { name })
      : post<{ success: boolean }>(`/tools/${name}/enable`),
  disable: (name: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('disable_tool', { name })
      : post<{ success: boolean }>(`/tools/${name}/disable`),
};

export const skillsApi = {
  list: () =>
    isTauri() ? apiInvoke<TauriSkillInfo[]>('list_skills') : get<TauriSkillInfo[]>('/skills'),
  get: (name: string) =>
    isTauri()
      ? apiInvoke<TauriSkillInfo>('get_skill', { name })
      : get<TauriSkillInfo>(`/skills/${name}`),
  load: (dir: string) =>
    isTauri()
      ? apiInvoke<LoadSkillsResponse>('load_skill', { name: dir })
      : post<LoadSkillsResponse>('/skills/load', { dir }),
  enable: (name: string) =>
    isTauri()
      ? apiInvoke<LoadSkillsResponse>('enable_skill', { name })
      : post<LoadSkillsResponse>(`/skills/${name}/enable`, {}),
  disable: (name: string) =>
    isTauri()
      ? apiInvoke<{
          success: boolean;
          requires_restart?: boolean;
          message?: string;
          skills?: TauriSkillInfo[];
        }>('disable_skill', { name })
      : post<{
          success: boolean;
          requires_restart?: boolean;
          message?: string;
          skills?: TauriSkillInfo[];
        }>(`/skills/${name}/disable`, {}),
  upload: (rootDir: string, files: { path: string; content: string }[]) =>
    isTauri()
      ? Promise.reject(new Error('Tauri 模式请使用“浏览”选择本地技能目录加载'))
      : post<{ message: string; loaded: string[]; skills: TauriSkillInfo[] }>('/skills/upload', {
          root_dir: rootDir,
          files,
        }),
  checkUpdates: (target = 'all') =>
    isTauri()
      ? apiInvoke<SkillUpdateStatus[]>('check_skill_updates', { target })
      : get<SkillUpdateStatus[]>(`/skills/updates?target=${encodeURIComponent(target)}`),
  sync: (target = 'all', force = false) =>
    isTauri()
      ? apiInvoke<SkillSyncResult[]>('sync_skills', { target, force })
      : post<SkillSyncResult[]>('/skills/sync', { target, force }),
};

export const mcpApi = {
  list: () =>
    isTauri()
      ? apiInvoke<TauriMcpServerInfo[]>('list_mcp_servers')
      : get<TauriMcpServerInfo[]>('/mcp'),
  get: (name: string) =>
    isTauri()
      ? apiInvoke<TauriMcpServerInfo>('get_mcp_server', { name })
      : get<TauriMcpServerInfo>(`/mcp/${name}`),
  connect: (req: { name: string; transport: { transport: string; [key: string]: unknown } }) =>
    isTauri()
      ? apiInvoke<{ success: boolean; name?: string; error?: string }>('connect_mcp_server', {
          name: req.name,
          transport: req.transport,
        })
      : post<TauriMcpServerInfo>('/mcp/connect', req),
  disconnect: (name: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('disconnect_mcp_server', { name })
      : post<{ success: boolean }>(`/mcp/${name}/disconnect`),
  toggle: (name: string, enabled: boolean) =>
    isTauri()
      ? apiInvoke<{ success: boolean; enabled: boolean; message?: string }>('toggle_mcp_server', {
          name,
          enabled,
        })
      : post<{ success: boolean; enabled: boolean; message?: string }>(`/mcp/${name}/toggle`, {
          enabled,
        }),
  getConfig: () =>
    isTauri() ? apiInvoke<McpConfig>('get_mcp_config') : get<McpConfig>('/mcp/config'),
  updateConfig: (config: McpConfig) =>
    isTauri()
      ? apiInvoke<{ success: boolean; message?: string }>('update_mcp_config', { config })
      : put<{ success: boolean; message?: string; errors?: string[] }>('/mcp/config', config),
};

export const memoryApi = {
  list: (namespace?: string) =>
    isTauri()
      ? apiInvoke<MemoryEntry[]>('list_memory', { namespace })
      : get<MemoryEntry[]>(`/memory/list${namespace ? `?namespace=${namespace}` : ''}`),
  add: (entry: { namespace: string; key: string; value: any }) =>
    isTauri()
      ? apiInvoke<{ success: boolean; key: string; message: string }>('add_memory', entry)
      : post<{ success: boolean; key: string; message: string }>('/memory', entry),
  search: (query: string, namespace?: string) =>
    isTauri()
      ? apiInvoke<MemoryEntry[]>('search_memory', { query, namespace })
      : post<MemoryEntry[]>('/memory/search', { query, namespace }),
  delete: (entry: { namespace: string; key: string }) =>
    isTauri()
      ? apiInvoke<{ success: boolean; message: string }>('delete_memory', entry)
      : post<{ success: boolean; message: string }>('/memory/delete', entry),
  namespaces: () =>
    isTauri()
      ? apiInvoke<NamespacesResponse>('list_namespaces')
      : get<NamespacesResponse>('/memory/namespaces'),
};

export const autoMemoryApi = {
  status: () =>
    isTauri()
      ? apiInvoke<AutoMemoryStatus>('get_auto_memory_status')
      : get<AutoMemoryStatus>('/auto-memory/status'),
  toggle: (enabled: boolean) =>
    isTauri()
      ? apiInvoke<AutoMemoryStatus>('toggle_auto_memory', { enabled })
      : post<AutoMemoryStatus>('/auto-memory/toggle', { enabled }),
  preview: () =>
    isTauri()
      ? apiInvoke<AutoMemoryPreview>('get_auto_memory_observations')
      : get<AutoMemoryPreview>('/auto-memory/observations'),
  extract: () =>
    isTauri()
      ? apiInvoke<AutoMemoryExtractResult>('extract_auto_memory')
      : post<AutoMemoryExtractResult>('/auto-memory/extract'),
};

export const configApi = {
  get: () => (isTauri() ? apiInvoke<ConfigInfo>('get_config') : get<ConfigInfo>('/config')),
  update: (cfg: Partial<ConfigInfo>) =>
    isTauri()
      ? apiInvoke<ConfigInfo>('update_config', { req: cfg })
      : put<ConfigInfo>('/config', cfg),
  getFull: () =>
    isTauri()
      ? apiInvoke<FullConfigResponse>('get_full_config')
      : get<FullConfigResponse>('/config/full'),
  updateFull: (cfg: Partial<FullConfigUpdateRequest>, _signal?: AbortSignal) =>
    isTauri()
      ? apiInvoke<FullConfigResponse>('update_full_config', { req: cfg })
      : put<FullConfigResponse>('/config/full', cfg, _signal),
};

export const permissionsApi = {
  getMode: () =>
    isTauri()
      ? apiInvoke<{ mode: string }>('get_permissions_mode')
      : get<{ mode: string }>('/permissions/mode'),
  setMode: (mode: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('set_permissions_mode', { mode })
      : put<{ success: boolean }>('/permissions/mode', { mode }),
  listRules: () =>
    isTauri()
      ? apiInvoke<PermissionRule[]>('list_permission_rules')
      : get<PermissionRule[]>('/permissions/rules'),
  addRule: (rule: Omit<PermissionRule, 'priority'>) =>
    isTauri()
      ? apiInvoke<PermissionRule>('add_permission_rule', {
          matcher: rule.name,
          behavior: rule.effect,
          source: 'manual',
        })
      : post<PermissionRule>('/permissions/rules', rule),
  removeRule: (name: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('remove_permission_rule', { matcher: name })
      : del<{ success: boolean }>(`/permissions/rules/${name}`),
};

export const auditApi = {
  logs: (offset?: number, limit?: number) =>
    isTauri()
      ? apiInvoke<{ logs: AuditLog[]; total: number; offset: number; limit: number }>(
          'get_audit_logs',
          { offset, limit }
        )
      : get<{ logs: AuditLog[]; total: number; offset: number; limit: number }>(
          `/audit/logs${offset !== undefined ? `?offset=${offset}&limit=${limit ?? 100}` : ''}`
        ),
  stats: () =>
    isTauri()
      ? apiInvoke<{ total: number; allowed: number; denied: number; asked: number }>(
          'get_audit_stats'
        )
      : get<{ total: number; allowed: number; denied: number; asked: number }>('/audit/stats'),
  clear: () =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('clear_audit_logs')
      : del<{ success: boolean }>('/audit/logs'),
};

export const workflowApi = {
  list: () =>
    isTauri() ? apiInvoke<WorkflowInfo[]>('list_workflows') : get<WorkflowInfo[]>('/workflow'),
  get: (id: string) =>
    isTauri()
      ? apiInvoke<WorkflowInfo>('get_workflow', { id })
      : get<WorkflowInfo>(`/workflow/${id}`),
  create: (definition: string, name?: string) =>
    isTauri()
      ? apiInvoke<WorkflowInfo>('create_workflow', { definition, name })
      : post<WorkflowInfo>('/workflow', { definition, name }),
  delete: (id: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('delete_workflow', { id })
      : del<{ success: boolean }>(`/workflow/${id}`),
  execute: (id: string, input?: unknown) =>
    isTauri()
      ? apiInvoke<{ success: boolean; result?: unknown }>('execute_workflow', { id, input })
      : post<{ success: boolean; result?: unknown }>(`/workflow/${id}/execute`, { input }),
};

export const sandboxApi = {
  status: () =>
    isTauri()
      ? apiInvoke<SandboxStatus>('get_sandbox_status')
      : get<SandboxStatus>('/sandbox/status'),
  config: () =>
    isTauri()
      ? apiInvoke<SandboxConfig>('get_sandbox_config')
      : get<SandboxConfig>('/sandbox/config'),
  updateConfig: (cfg: SandboxConfig) =>
    isTauri()
      ? apiInvoke<SandboxConfig>('update_sandbox_config', { config: cfg })
      : put<SandboxConfig>('/sandbox/config', cfg),
  execute: (req: SandboxExecuteRequest) =>
    isTauri()
      ? apiInvoke<SandboxExecuteResult>('execute_sandbox', {
          code: req.code,
          language: req.language,
        })
      : post<SandboxExecuteResult>('/sandbox/execute', req),
};

export const compressApi = {
  trigger: (options?: { keep_messages?: number }) =>
    isTauri()
      ? apiInvoke<CompressResponse>('compress_context')
      : post<CompressResponse>('/compress', options),
  getStats: () =>
    isTauri()
      ? apiInvoke<CompressionStats>('get_compression_stats')
      : get<CompressionStats>('/compress/stats'),
};

export const extractApi = {
  extract: (input: string, schema: object, schema_name?: string) =>
    isTauri()
      ? apiInvoke<ExtractResponse>('extract_data', { input, schema, schema_name })
      : post<ExtractResponse>('/extract', { input, schema, schema_name }),
  validateSchema: (schema: object) =>
    isTauri()
      ? apiInvoke<ValidateSchemaResponse>('validate_schema', { schema })
      : post<ValidateSchemaResponse>('/extract/validate', { schema }),
  getExamples: () =>
    isTauri()
      ? apiInvoke<ExtractExample[]>('get_extract_examples')
      : get<ExtractExample[]>('/extract/examples'),
};

export const conversationApi = {
  list: () =>
    isTauri()
      ? apiInvoke<ConversationListItem[]>('list_conversations')
      : get<ConversationListItem[]>('/conversations'),
  save: (data: { id: string; title: string; messages: SavedMessage[]; model?: string }) =>
    isTauri()
      ? apiInvoke<{ success: boolean; id: string }>('save_conversation', {
          id: data.id,
          title: data.title,
          messages: data.messages,
        })
      : post<{ success: boolean; id: string }>('/conversations', data),
  get: (id: string) =>
    isTauri()
      ? apiInvoke<ConversationRecord>('get_conversation', { id })
      : get<ConversationRecord>(`/conversations/${id}`),
  update: (id: string, data: { title?: string; messages?: SavedMessage[] }) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('update_conversation', {
          id,
          title: data.title,
          messages: data.messages,
        })
      : put<{ success: boolean }>(`/conversations/${id}`, data),
  branch: (id: string, userTurnIndex: number) =>
    isTauri()
      ? apiInvoke<{
          success: boolean;
          id: string;
          source_id: string;
          message_count: number;
          target_content: string;
        }>('branch_conversation', { id, userTurnIndex, user_turn_index: userTurnIndex })
      : post<{
          success: boolean;
          id: string;
          source_id: string;
          message_count: number;
          target_content: string;
        }>(`/conversations/${id}/branch`, { user_turn_index: userTurnIndex }),
  delete: (id: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('delete_conversation', { id })
      : del<{ success: boolean }>(`/conversations/${id}`),
  export: (id: string) =>
    isTauri()
      ? apiInvoke<{ format: string; content: string; id: string }>('export_conversation', { id })
      : get<{ format: string; content: string; id: string }>(`/conversations/${id}/export`),
  restore: (id: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; message_count: number; conversation_id: string }>(
          'restore_conversation',
          { id }
        )
      : post<{ success: boolean; message_count: number; conversation_id: string }>(
          `/conversations/${id}/restore`
        ),
  search: (query: string, limit?: number) =>
    isTauri()
      ? apiInvoke<ConversationListItem[]>('search_conversations', { query, limit })
      : get<ConversationListItem[]>(`/conversations/search?q=${encodeURIComponent(query)}`),
};

export const toolExecutionApi = {
  list: (conversationId: string) =>
    apiInvoke<ToolExecution[]>('list_tool_executions', { conversationId }),
  detail: (detailRef: string) =>
    apiInvoke<ToolExecutionDetailManifest>('get_tool_execution_detail', { detailRef }),
  readOutput: (detailRef: string, cursor?: string | null, limit = 64 * 1024) =>
    apiInvoke<ToolExecutionDetailPage>('read_tool_execution_output', {
      detailRef,
      cursor: cursor ?? null,
      limit,
    }),
};

export const contextApi = {
  get: () =>
    isTauri() ? apiInvoke<ContextStats>('get_context_stats') : get<ContextStats>('/context'),
};

export interface BackgroundTask {
  id: string;
  description: string;
  status: string;
  created_at: string;
  updated_at: string;
  result?: string;
  error?: string;
  kind?: string;
  progress?: number;
  progress_pct?: number;
  progress_phase?: string;
  progress_message?: string;
  eta_secs?: number;
  /** Phase 3.4: "run" for AgentChat/Composite runs, "framework" for pipeline. */
  source?: 'run' | 'framework';
}

export interface SubmitTaskRequest {
  kind: string;
  description: string;
  params: Record<string, unknown>;
}

export const tasksApi = {
  list: () =>
    isTauri() ? apiInvoke<BackgroundTask[]>('list_tasks') : get<BackgroundTask[]>('/tasks'),
  get: (id: string) =>
    isTauri() ? apiInvoke<BackgroundTask>('get_task', { id }) : get<BackgroundTask>(`/tasks/${id}`),
  submit: (req: SubmitTaskRequest) =>
    isTauri()
      ? apiInvoke<{ success: boolean; task_id: string }>('submit_task', {
          kind: req.kind,
          description: req.description,
          params: req.params,
        })
      : post<{ success: boolean; task_id: string }>('/tasks', req),
  cancel: (id: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; task_id: string }>('cancel_task', { id })
      : post<{ success: boolean; task_id: string }>(`/tasks/${id}/cancel`),
};

// ── TaskRuntime API (complex-task runs, plans, todos, events, execution) ─
// Read paths mirror tasksApi; mutations drive the shared run lifecycle.
// All Tauri args are snake_case.
export const taskRuntimeApi = {
  // ── Reads ────────────────────────────────────────────────────────────
  getRun: (runId: string) =>
    isTauri()
      ? apiInvoke<TaskRun | null>('get_task_run', { runId })
      : get<TaskRun | null>(`/task_runtime/runs/${runId}`),
  latestRunForConversation: (conversationId: string) =>
    isTauri()
      ? apiInvoke<TaskRun | null>('latest_task_run_for_conversation', {
          conversationId,
        })
      : get<TaskRun | null>(`/task_runtime/conversations/${conversationId}/latest_run`),
  listRuns: (statuses?: string[]) =>
    isTauri()
      ? apiInvoke<TaskRun[]>('list_task_runs', { statuses: statuses ?? null })
      : get<TaskRun[]>('/task_runtime/runs'),
  getPlan: (runId: string) =>
    isTauri()
      ? apiInvoke<TaskPlan | null>('get_task_plan', { runId })
      : get<TaskPlan | null>(`/task_runtime/runs/${runId}/plan`),
  listTodos: (runId: string) =>
    isTauri()
      ? apiInvoke<TodoItem[]>('list_task_todos', { runId })
      : get<TodoItem[]>(`/task_runtime/runs/${runId}/todos`),
  listEvents: (runId: string, sinceSeq?: string) =>
    isTauri()
      ? apiInvoke<RuntimeTaskEvent[]>('list_task_events', {
          runId,
          sinceSeq: sinceSeq ?? null,
        })
      : get<RuntimeTaskEvent[]>(`/task_runtime/runs/${runId}/events`),
  listArtifacts: (runId: string) =>
    isTauri()
      ? apiInvoke<RuntimeArtifact[]>('list_task_artifacts', { runId })
      : get<RuntimeArtifact[]>(`/task_runtime/runs/${runId}/artifacts`),
  getProgressLedger: (runId: string) =>
    isTauri()
      ? apiInvoke<string>('get_progress_ledger', { runId })
      : get<string>(`/task_runtime/runs/${runId}/progress.md`),
  listReviews: (runId: string, taskId: string) =>
    isTauri()
      ? apiInvoke<ReviewResult[]>('list_task_reviews', { runId, taskId })
      : get<ReviewResult[]>(`/task_runtime/runs/${runId}/tasks/${taskId}/reviews`),
  getTaskSummary: (runId: string, taskId: string) =>
    isTauri()
      ? apiInvoke<TaskExecutionSummary | null>('get_task_summary', { runId, taskId })
      : get<TaskExecutionSummary | null>(`/task_runtime/runs/${runId}/tasks/${taskId}/summary`),
  listRecoveryBlockers: (runId: string) =>
    isTauri()
      ? apiInvoke<RecoveryBlocker[]>('list_recovery_blockers', { runId })
      : get<RecoveryBlocker[]>(`/task_runtime/runs/${runId}/recovery_blockers`),

  cancelRun: (runId: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; run_id: string }>('cancel_task_run', {
          runId,
        })
      : post<{ success: boolean; run_id: string }>(`/task_runtime/runs/${runId}/cancel`),
  pauseRun: (runId: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; run_id: string }>('pause_task_run', { runId })
      : post<{ success: boolean; run_id: string }>(`/task_runtime/runs/${runId}/pause`),

  // ── Dynamic task operations ──────────────────────────────────────────
  resumeRun: (runId: string) =>
    isTauri()
      ? apiInvoke<{ kind: string; run_id: string }>('resume_task_run', { runId })
      : post(`/task_runtime/runs/${runId}/resume`),
  retryBlockedTask: (runId: string, taskId: string) =>
    isTauri()
      ? apiInvoke<{ kind: string; run_id: string; task_id: string; next_attempt: number }>(
          'retry_blocked_task',
          { runId, taskId }
        )
      : post(`/task_runtime/runs/${runId}/tasks/${taskId}/retry`),
  resolveRecoveryTask: (runId: string, taskId: string, decision: 'retry' | 'skip') =>
    isTauri()
      ? apiInvoke<void>('resolve_recovery_task', { runId, taskId, decision })
      : post(`/task_runtime/runs/${runId}/tasks/${taskId}/resolve_recovery`, { decision }),
  updateTasks: (runId: string, request: TaskUpdateRequest) =>
    isTauri()
      ? apiInvoke<TaskPlan>('update_tasks', { runId, request })
      : post<TaskPlan>(`/task_runtime/runs/${runId}/tasks/update`, request),

  // ── Interaction mode ─────────────────────────────────────────────────
  setInteractionMode: (mode: number) =>
    isTauri()
      ? apiInvoke<number>('set_interaction_mode', { mode })
      : post<number>('/task_runtime/interaction_mode', { mode }),
  getInteractionMode: () =>
    isTauri()
      ? apiInvoke<number>('get_interaction_mode')
      : get<number>('/task_runtime/interaction_mode'),
};

// ── Durable run diagnostics API ──────────────────────────────────────

export interface DiagnosticRunSummary {
  diagnostic_id: string;
  parent_run_id?: string | null;
  trace_count: number;
  status: string;
  input_preview: string;
  started_at: string;
  finished_at?: string | null;
  agents: string[];
  models: string[];
  total_input_tokens: number;
  total_output_tokens: number;
  total_cached_input_tokens: number;
  llm_calls: number;
  calls_missing_usage: number;
}

export interface LlmContextBreakdown {
  system_tokens: number;
  user_tokens: number;
  assistant_tokens: number;
  tool_tokens: number;
  summary_tokens: number;
  memory_tokens: number;
}

export interface LlmCallDiagnostic {
  sequence: number;
  source: 'provider' | 'estimated';
  input_tokens?: number | null;
  output_tokens?: number | null;
  cached_input_tokens?: number | null;
  cache_creation_input_tokens?: number | null;
  estimated_context_tokens: number;
  protected_context_tokens: number;
  protected_message_count: number;
  context_limit_tokens: number;
  context_breakdown: LlmContextBreakdown;
  stable_prefix_hash: string;
  system_prefix_hash: string;
  tools_schema_hash: string;
  history_hash: string;
  message_count: number;
  tool_count: number;
  duration_ms: number;
}

export interface TraceInvocationDiagnostic {
  trace_run_id: string;
  agent_name: string;
  model: string;
  provider?: string | null;
  turn_id?: string | null;
  execution_id?: string | null;
  status: string;
  started_at: string;
  finished_at?: string | null;
  llm_calls: LlmCallDiagnostic[];
}

export interface RunDiagnostics {
  diagnostic_id: string;
  parent_run_id?: string | null;
  traces: TraceInvocationDiagnostic[];
  usage: {
    provider_reported_calls: number;
    calls_missing_usage: number;
    total_input_tokens: number;
    total_output_tokens: number;
    total_cached_input_tokens: number;
    total_cache_creation_input_tokens: number;
  };
  cache: {
    read_rate?: number | null;
    system_prefix_hash_changes: number;
    tools_schema_hash_changes: number;
    stable_prefix_hash_changes: number;
  };
  context: {
    latest_provider_input_tokens?: number | null;
    latest_estimated_context_tokens: number;
    latest_context_limit_tokens: number;
    latest_breakdown: LlmContextBreakdown;
    max_protected_context_tokens: number;
    max_protected_message_count: number;
  };
  compressions: Array<{
    trace_run_id: string;
    sequence: number;
    source: string;
    before_messages: number;
    after_messages: number;
    before_tokens: number;
    after_tokens: number;
    protected_context_tokens: number;
    protected_message_count: number;
  }>;
  issues: Array<{
    kind: string;
    severity: 'info' | 'warning' | 'critical';
    message: string;
  }>;
  prompt_assembly?: {
    estimated_tokens: number;
    modules: Array<{
      name: string;
      estimated_tokens: number;
      included: boolean;
      truncated: boolean;
      content_hash: string;
      stable_prefix: boolean;
    }>;
  } | null;
}

export const runDiagnosticsApi = {
  list: () =>
    isTauri()
      ? apiInvoke<DiagnosticRunSummary[]>('list_diagnostic_runs')
      : get<DiagnosticRunSummary[]>('/run-diagnostics'),
  get: (diagnosticId: string) =>
    isTauri()
      ? apiInvoke<RunDiagnostics>('get_run_diagnostics', { diagnosticId })
      : get<RunDiagnostics>(`/run-diagnostics/${diagnosticId}`),
};

// ── Files API ───────────────────────────────────────────────────────

export interface FileEntry {
  name: string;
  path: string;
  is_dir: boolean;
  size: number;
  modified?: string;
  extension?: string;
}

export interface FileTreeNode {
  name: string;
  path: string;
  is_dir: boolean;
  children?: FileTreeNode[];
}

export interface FileContent {
  workspace_id: string;
  path: string;
  content: string;
  size: number;
  language?: string;
  kind: 'text' | 'image' | 'pdf' | 'binary';
  mime_type?: string | null;
  data_url?: string | null;
  revision: string;
}

export interface WorkspaceChange {
  path: string;
  status: 'modified' | 'added' | 'deleted';
}

export interface DiffLine {
  tag: 'equal' | 'insert' | 'delete';
  old_line?: number;
  new_line?: number;
  content: string;
}

export interface DiffHunk {
  old_start: number;
  old_count: number;
  new_start: number;
  new_count: number;
  lines: DiffLine[];
}

export interface DiffResult {
  path: string;
  old_content: string;
  new_content: string;
  hunks: DiffHunk[];
}

export const filesApi = {
  list: (path?: string) =>
    isTauri()
      ? apiInvoke<FileEntry[]>('list_files', { path })
      : get<FileEntry[]>(`/files/list${path ? `?path=${encodeURIComponent(path)}` : ''}`),
  read: (path: string) =>
    isTauri()
      ? apiInvoke<FileContent>('read_file', { path })
      : get<FileContent>(`/files/read?path=${encodeURIComponent(path)}`),
  write: (path: string, content: string, expectedWorkspaceId: string, expectedRevision: string) =>
    isTauri()
      ? apiInvoke<FileContent>('write_file', {
          path,
          content,
          expectedWorkspaceId,
          expectedRevision,
        })
      : put<FileContent>(`/files/write?path=${encodeURIComponent(path)}`, {
          content,
          expected_workspace_id: expectedWorkspaceId,
          expected_revision: expectedRevision,
        }),
  diff: (path: string, gitRef = 'HEAD') =>
    isTauri()
      ? apiInvoke<DiffResult>('diff_file', { path, git_ref: gitRef })
      : get<DiffResult>(`/files/diff?path=${encodeURIComponent(path)}&git_ref=${gitRef}`),
  tree: (depth = 3) =>
    isTauri()
      ? apiInvoke<FileTreeNode[]>('file_tree', { depth })
      : get<FileTreeNode[]>(`/files/tree?depth=${depth}`),
  changes: () =>
    isTauri()
      ? apiInvoke<WorkspaceChange[]>('workspace_changes')
      : get<WorkspaceChange[]>('/files/changes'),
};

// ── File-backed analysis API ───────────────────────────────────────

export type AnalysisLanguage = 'python' | 'r';
export type AnalysisRunStatus = 'succeeded' | 'failed' | 'cancelled' | 'timed_out';

export interface AnalysisManifest {
  contract_version: number;
  analysis_id: string;
  title: string;
  language: AnalysisLanguage;
  script_path: string;
  input_paths: string[];
  parameters: unknown;
  random_seed?: number | null;
  created_at: string;
  updated_at: string;
}

export interface AnalysisFileFingerprint {
  path: string;
  available: boolean;
  bytes?: number | null;
  sha256?: string | null;
}

export interface AnalysisOutputArtifact {
  path: string;
  absolute_path: string;
  kind: string;
  bytes: number;
  sha256: string;
}

export interface AnalysisRunRecord {
  contract_version: number;
  run_id: string;
  analysis_id: string;
  status: AnalysisRunStatus;
  started_at: string;
  finished_at: string;
  duration_ms: number;
  script: AnalysisFileFingerprint;
  inputs: AnalysisFileFingerprint[];
  parameters: unknown;
  parameters_sha256: string;
  random_seed?: number | null;
  outputs: AnalysisOutputArtifact[];
  environment: Record<string, string>;
  exit_code?: number | null;
  sandbox_type?: string | null;
  output: string;
  error?: string | null;
  output_truncated: boolean;
}

export interface AnalysisSummary {
  analysis_id: string;
  title: string;
  language: AnalysisLanguage;
  script_path: string;
  updated_at: string;
  stale: boolean;
  stale_reasons: string[];
  last_run_status?: AnalysisRunStatus | null;
  last_run_at?: string | null;
}

export interface AnalysisDocument {
  manifest: AnalysisManifest;
  script: string;
  script_revision: string;
  stale: boolean;
  stale_reasons: string[];
  last_run?: AnalysisRunRecord | null;
  outputs: AnalysisOutputArtifact[];
}

export interface SaveAnalysisInput {
  title: string;
  script: string;
  expectedScriptRevision: string;
  inputPaths: string[];
  parameters: unknown;
  randomSeed?: number | null;
}

function analysisRequiresDesktop<T>(): Promise<T> {
  return Promise.reject(new Error('文件化分析工作台需要 EKO 桌面运行时'));
}

export const analysisApi = {
  list: () =>
    isTauri()
      ? apiInvoke<AnalysisSummary[]>('list_analyses')
      : analysisRequiresDesktop<AnalysisSummary[]>(),
  create: (title: string, language: AnalysisLanguage) =>
    isTauri()
      ? apiInvoke<AnalysisDocument>('create_analysis', { title, language })
      : analysisRequiresDesktop<AnalysisDocument>(),
  get: (analysisId: string) =>
    isTauri()
      ? apiInvoke<AnalysisDocument>('get_analysis', { analysisId })
      : analysisRequiresDesktop<AnalysisDocument>(),
  save: (analysisId: string, input: SaveAnalysisInput) =>
    isTauri()
      ? apiInvoke<AnalysisDocument>('save_analysis', {
          analysisId,
          title: input.title,
          script: input.script,
          expectedScriptRevision: input.expectedScriptRevision,
          inputPaths: input.inputPaths,
          parameters: input.parameters,
          randomSeed: input.randomSeed ?? null,
        })
      : analysisRequiresDesktop<AnalysisDocument>(),
  run: (analysisId: string) =>
    isTauri()
      ? apiInvoke<AnalysisDocument>('run_analysis', { analysisId })
      : analysisRequiresDesktop<AnalysisDocument>(),
  cancel: (analysisId: string) =>
    isTauri()
      ? apiInvoke<boolean>('cancel_analysis', { analysisId })
      : analysisRequiresDesktop<boolean>(),
};

// ── Terminal API ────────────────────────────────────────────────────

export interface TerminalSession {
  id: string;
  cwd: string;
  created_at: string;
}

export const terminalApi = {
  list: () =>
    isTauri()
      ? apiInvoke<TerminalSession[]>('list_terminal_sessions')
      : get<TerminalSession[]>('/terminal'),
  create: (cwd?: string) =>
    isTauri()
      ? apiInvoke<TerminalSession>('create_terminal', { id: `term-${Date.now()}`, cwd })
      : post<TerminalSession>('/terminal', { cwd }),
  close: (id: string) =>
    isTauri()
      ? apiInvoke<{ closed: string }>('close_terminal', { id })
      : del<{ closed: string }>(`/terminal/${id}`),
  wsUrl: (id: string) => {
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    return `${protocol}//${window.location.host}/api/terminal/${id}/ws`;
  },
};

// ── Papers API ──────────────────────────────────────────────────────

export interface Paper {
  contract_version: number;
  id: string;
  source_kind:
    | 'journal_article'
    | 'preprint'
    | 'conference_paper'
    | 'book'
    | 'dataset'
    | 'guideline'
    | 'trial_registration'
    | 'web'
    | 'other';
  title: string;
  authors: string[];
  abstract_text?: string;
  doi?: string;
  pmid?: string;
  pmcid?: string;
  arxiv_id?: string;
  openalex_id?: string;
  zotero_key?: string;
  clinical_trial_id?: string;
  year?: number;
  venue?: string;
  url?: string;
  tags: string[];
  notes?: string;
  pdf_path?: string;
  provenance: Array<{
    provider: string;
    query?: string;
    retrieved_at: string;
    record_url?: string;
  }>;
  europe_pmc?: {
    citation_ids: string[];
    reference_ids: string[];
    biomedical_entities: Array<{
      name: string;
      semantic_type?: string;
      frequency?: number;
    }>;
    full_text_path?: string;
    enriched_at?: string;
  };
  added_at: string;
  updated_at: string;
}

export interface CreatePaperRequest {
  source_kind?: Paper['source_kind'];
  title: string;
  authors?: string[];
  abstract_text?: string;
  doi?: string;
  pmid?: string;
  pmcid?: string;
  arxiv_id?: string;
  openalex_id?: string;
  zotero_key?: string;
  clinical_trial_id?: string;
  year?: number;
  venue?: string;
  url?: string;
  pdf_path?: string;
  tags?: string[];
  notes?: string;
  provenance?: Paper['provenance'];
  europe_pmc?: Paper['europe_pmc'];
}

export interface EvidenceRecord {
  contract_version: number;
  id: string;
  source_id: string;
  review_id?: string;
  dimension: string;
  claim: string;
  excerpt?: string;
  locator?: string;
  evidence_type?: string;
  population?: string;
  intervention?: string;
  comparator?: string;
  outcome?: string;
  effect?: string;
  limitations?: string;
  certainty?: string;
  harms?: string[];
  contraindications?: string[];
  conflicts_of_interest?: string[];
  guideline_conflicts?: string[];
  extrapolation_limits?: string[];
  tags: string[];
  created_at: string;
  updated_at: string;
}

export type UpsertEvidenceRequest = Omit<
  EvidenceRecord,
  'contract_version' | 'id' | 'created_at' | 'updated_at'
> & { id?: string };

export type ReviewDomain = 'academic' | 'medical';
export type ScreeningStage = 'title_abstract' | 'full_text';
export type ScreeningDecisionValue = 'pending' | 'include' | 'exclude' | 'maybe';
export type RiskJudgment = 'low' | 'some_concerns' | 'high';
export type GradeCertainty = 'high' | 'moderate' | 'low' | 'very_low';
export type GradeConcern = 'not_serious' | 'serious' | 'very_serious';

export interface SystematicReviewRecord {
  contract_version: number;
  id: string;
  title: string;
  domain: ReviewDomain;
  status: string;
  protocol: {
    objective: string;
    question: string;
    registration?: string;
    date_range?: string;
    databases: string[];
    search_strategies: Array<{
      database: string;
      query: string;
      searched_at?: string;
      result_count?: number;
    }>;
    eligibility: { inclusion: string[]; exclusion: string[] };
    pico?: {
      population: string;
      intervention: string;
      comparator: string;
      outcomes: string[];
    };
    peco?: {
      population: string;
      exposure: string;
      comparator: string;
      outcomes: string[];
    };
  };
  source_ids: string[];
  screening: Array<{
    source_id: string;
    stage: ScreeningStage;
    decision: ScreeningDecisionValue;
    reason?: string;
    reviewer?: string;
    decided_at: string;
  }>;
  risk_of_bias: Array<{
    id: string;
    source_id: string;
    result_id?: string;
    tool: 'rob2' | 'robins_i' | 'custom';
    domains: Array<{ domain: string; judgment: RiskJudgment; rationale: string }>;
    overall: RiskJudgment;
    rationale: string;
    assessed_at: string;
  }>;
  grade: Array<{
    id: string;
    outcome: string;
    relative_effect?: string;
    absolute_effect?: string;
    participants?: number;
    studies?: number;
    certainty: GradeCertainty;
    risk_of_bias: { concern: GradeConcern; explanation: string };
    inconsistency: { concern: GradeConcern; explanation: string };
    indirectness: { concern: GradeConcern; explanation: string };
    imprecision: { concern: GradeConcern; explanation: string };
    publication_bias: { concern: GradeConcern; explanation: string };
    applicability?: string;
  }>;
  prisma: {
    additional_identified: number;
    duplicates_removed: number;
    reports_not_retrieved: number;
  };
  medical?: {
    harms: string[];
    contraindications: string[];
    conflicts_of_interest: string[];
    guideline_conflicts: string[];
    extrapolation_limits: string[];
    guideline_source_ids: string[];
  };
  created_at: string;
  updated_at: string;
}

export interface PrismaFlow {
  records_identified: number;
  duplicates_removed: number;
  records_screened: number;
  records_excluded: number;
  reports_sought: number;
  reports_not_retrieved: number;
  reports_assessed: number;
  reports_excluded: number;
  studies_included: number;
}

export interface SystematicReviewDocument {
  record: SystematicReviewRecord;
  revision: string;
  prisma_flow: PrismaFlow;
}

export interface SystematicReviewSummary {
  id: string;
  title: string;
  domain: ReviewDomain;
  status: string;
  source_count: number;
  included_count: number;
  updated_at: string;
}

export type ResearchProvider = 'openalex' | 'crossref' | 'europe_pmc';
export interface ScholarlyIngestResult {
  provider: ResearchProvider;
  total?: number;
  created: number;
  updated: number;
  sources: Paper[];
}

export interface ZoteroSyncRequest {
  library_kind: 'user' | 'group';
  library_id: string;
  api_key: string;
  limit?: number;
  source_ids: string[];
}

export interface ZoteroSyncResult {
  imported: number;
  updated: number;
  exported: number;
  sources: Paper[];
  provider_response?: unknown;
}

export interface EuropePmcEnrichmentResult {
  source: Paper;
  warnings: string[];
}

export interface CitationAuditIssue {
  severity: 'error' | 'warning' | 'info';
  code: string;
  message: string;
  source_id?: string;
  evidence_id?: string;
}

export interface CitationAuditReport {
  review_id: string;
  checked_at: string;
  source_count: number;
  evidence_count: number;
  error_count: number;
  warning_count: number;
  issues: CitationAuditIssue[];
}

export type ReviewExportFormat =
  | 'markdown'
  | 'pdf'
  | 'docx'
  | 'json'
  | 'csv'
  | 'bibtex'
  | 'ris'
  | 'all';
export interface ReviewExportArtifact {
  review_id: string;
  format: Exclude<ReviewExportFormat, 'all'>;
  path: string;
  bytes: number;
  citation_audit: CitationAuditReport;
}

function researchRequiresDesktop<T>(): Promise<T> {
  return Promise.reject(new Error('文件化研究工作台需要 EKO 桌面运行时'));
}

export const papersApi = {
  list: (params?: { tag?: string; search?: string }) =>
    isTauri()
      ? apiInvoke<Paper[]>('list_papers', params)
      : (() => {
          const q = new URLSearchParams();
          if (params?.tag) q.set('tag', params.tag);
          if (params?.search) q.set('search', params.search);
          const qs = q.toString();
          return get<Paper[]>(`/papers${qs ? `?${qs}` : ''}`);
        })(),
  get: (id: string) =>
    isTauri() ? apiInvoke<Paper>('get_paper', { id }) : get<Paper>(`/papers/${id}`),
  create: (req: CreatePaperRequest) =>
    isTauri() ? apiInvoke<Paper>('create_paper', { request: req }) : post<Paper>('/papers', req),
  delete: (id: string) =>
    isTauri()
      ? apiInvoke<{ deleted: string }>('delete_paper', { id })
      : del<{ deleted: string }>(`/papers/${id}`),
  updateNotes: (id: string, notes: string) =>
    isTauri()
      ? apiInvoke<Paper>('update_paper_notes', { id, notes })
      : put<Paper>(`/papers/${id}/notes`, { notes }),
  addTags: (id: string, tags: string[]) =>
    isTauri()
      ? apiInvoke<Paper>('add_paper_tags', { id, tags })
      : post<Paper>(`/papers/${id}/tags`, { tags }),
  search: (request: {
    provider: ResearchProvider;
    query: string;
    limit?: number;
    mailto?: string;
  }) =>
    isTauri()
      ? apiInvoke<ScholarlyIngestResult>('search_scholarly_sources', { request })
      : researchRequiresDesktop<ScholarlyIngestResult>(),
  importZotero: (request: ZoteroSyncRequest) =>
    isTauri()
      ? apiInvoke<ZoteroSyncResult>('import_zotero_library', { request })
      : researchRequiresDesktop<ZoteroSyncResult>(),
  exportZotero: (request: ZoteroSyncRequest) =>
    isTauri()
      ? apiInvoke<ZoteroSyncResult>('export_zotero_library', { request })
      : researchRequiresDesktop<ZoteroSyncResult>(),
  enrichEuropePmc: (sourceId: string) =>
    isTauri()
      ? apiInvoke<EuropePmcEnrichmentResult>('enrich_paper_europe_pmc', { sourceId })
      : researchRequiresDesktop<EuropePmcEnrichmentResult>(),
};

export const evidenceApi = {
  list: (params?: { sourceId?: string; reviewId?: string }) =>
    isTauri()
      ? apiInvoke<EvidenceRecord[]>('list_research_evidence', params)
      : researchRequiresDesktop<EvidenceRecord[]>(),
  upsert: (request: UpsertEvidenceRequest) =>
    isTauri()
      ? apiInvoke<EvidenceRecord>('upsert_research_evidence', { request })
      : researchRequiresDesktop<EvidenceRecord>(),
  delete: (evidenceId: string) =>
    isTauri()
      ? apiInvoke<boolean>('delete_research_evidence', { evidenceId })
      : researchRequiresDesktop<boolean>(),
};

export const systematicReviewsApi = {
  list: () =>
    isTauri()
      ? apiInvoke<SystematicReviewSummary[]>('list_systematic_reviews')
      : researchRequiresDesktop<SystematicReviewSummary[]>(),
  create: (request: { title: string; question: string; domain: ReviewDomain }) =>
    isTauri()
      ? apiInvoke<SystematicReviewDocument>('create_systematic_review', { request })
      : researchRequiresDesktop<SystematicReviewDocument>(),
  get: (reviewId: string) =>
    isTauri()
      ? apiInvoke<SystematicReviewDocument>('get_systematic_review', { reviewId })
      : researchRequiresDesktop<SystematicReviewDocument>(),
  save: (document: SystematicReviewDocument) =>
    isTauri()
      ? apiInvoke<SystematicReviewDocument>('save_systematic_review', {
          reviewId: document.record.id,
          record: document.record,
          expectedRevision: document.revision,
        })
      : researchRequiresDesktop<SystematicReviewDocument>(),
  delete: (reviewId: string) =>
    isTauri()
      ? apiInvoke<boolean>('delete_systematic_review', { reviewId })
      : researchRequiresDesktop<boolean>(),
  audit: (reviewId: string) =>
    isTauri()
      ? apiInvoke<CitationAuditReport>('audit_systematic_review', { reviewId })
      : researchRequiresDesktop<CitationAuditReport>(),
  export: (reviewId: string, format: ReviewExportFormat) =>
    isTauri()
      ? apiInvoke<ReviewExportArtifact[]>('export_systematic_review', { reviewId, format })
      : researchRequiresDesktop<ReviewExportArtifact[]>(),
};

// ── Workspace API ──

export interface Workspace {
  id: string;
  name: string;
  root: string;
  project_root?: string;
  kind: { type: string } & Record<string, unknown>;
  metadata: {
    description?: string;
    tags: string[];
  };
  created_at: string;
  last_active: string;
}

export interface WorkspaceListResponse {
  workspaces: Workspace[];
  count: number;
}

export const workspaceApi = {
  list: () =>
    isTauri()
      ? apiInvoke<WorkspaceListResponse>('list_workspaces')
      : get<WorkspaceListResponse>('/workspaces'),
  create: (name: string, kind?: string, root?: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; workspace: Workspace }>('create_workspace', {
          name,
          kind,
          root,
        })
      : post<{ success: boolean; workspace: Workspace }>('/workspaces', { name, kind, root }),
  current: () =>
    isTauri()
      ? apiInvoke<{ workspace: Workspace | null; active: boolean }>('get_current_workspace')
      : get<{ workspace: Workspace | null; active: boolean }>('/workspaces/current'),
  get: (id: string) =>
    isTauri()
      ? apiInvoke<{ workspace: Workspace }>('get_workspace', { id }).then((r) => r.workspace)
      : get<Workspace>(`/workspaces/${id}`),
  switch: (id: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; workspace: Workspace }>('switch_workspace', { id })
      : post<{ success: boolean; workspace: Workspace }>(`/workspaces/${id}/switch`, {}),
  exit: () =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('exit_workspace')
      : post<{ success: boolean }>('/workspaces/exit', {}),
  delete: (id: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('delete_workspace', { id })
      : del<{ success: boolean }>(`/workspaces/${id}`),
  linkProject: (id: string, path: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; workspace: Workspace }>('link_project', { id, path })
      : post<{ success: boolean; workspace: Workspace }>(`/workspaces/${id}/link`, { path }),
  defaultRoot: (name: string) =>
    isTauri()
      ? apiInvoke<{ default_root: string }>('get_default_root', { name })
      : get<{ default_root: string }>(`/workspaces/default-root/${encodeURIComponent(name)}`),
};

// ── Evolution API (自进化) ─────────────────────────────────────────

export const evolutionApi = {
  review: (runId?: string) =>
    isTauri()
      ? apiInvoke<{
          success: boolean;
          run_id: string;
          actions: string[];
          nothing_to_save: boolean;
          candidate?: {
            kind: 'user_preference' | 'project_fact' | 'debugging_lesson' | 'skill';
            content: string;
            evidence: string;
            confidence: number;
            persisted: boolean;
          } | null;
          evidence_candidate?: EvidenceCandidate | null;
          error?: string | null;
        }>('review_run', { run_id: runId })
      : post<{
          success: boolean;
          run_id: string;
          actions: string[];
          nothing_to_save: boolean;
          candidate?: {
            kind: 'user_preference' | 'project_fact' | 'debugging_lesson' | 'skill';
            content: string;
            evidence: string;
            confidence: number;
            persisted: boolean;
          } | null;
          evidence_candidate?: EvidenceCandidate | null;
          error?: string | null;
        }>('/evolution/review', { run_id: runId }),
  listEvidence: (status: EvidenceInboxFilter = 'pending') =>
    isTauri()
      ? apiInvoke<{ candidates: EvidenceCandidate[]; count: number; path: string }>(
          'list_evidence_candidates',
          { status }
        )
      : get<{ candidates: EvidenceCandidate[]; count: number; path: string }>(
          `/evolution/evidence?status=${encodeURIComponent(status)}`
        ),
  evidenceAction: (
    action: 'edit' | 'accept' | 'reject' | 'undo',
    candidateId: string,
    content?: string
  ) =>
    isTauri()
      ? apiInvoke<{ success: boolean; candidate: EvidenceCandidate }>('evidence_candidate_action', {
          action,
          candidate_id: candidateId,
          content,
        })
      : post<{ success: boolean; candidate: EvidenceCandidate }>('/evolution/evidence/action', {
          action,
          candidate_id: candidateId,
          content,
        }),
  curator: (action: string, skillName?: string) =>
    isTauri()
      ? apiInvoke<{
          success: boolean;
          status?: CuratorStatus;
          transitions?: CuratorTransition[];
          count?: number;
          pinned?: string;
          unpinned?: string;
          error?: string;
        }>('curator_action', { action, skill_name: skillName })
      : post<{
          success: boolean;
          status?: CuratorStatus;
          transitions?: CuratorTransition[];
          count?: number;
          pinned?: string;
          unpinned?: string;
          error?: string;
        }>('/evolution/curator', { action, skill_name: skillName }),
  dashboard: () =>
    isTauri()
      ? apiInvoke<{ metrics: DashboardMetrics }>('get_evolution_dashboard')
      : get<{ metrics: DashboardMetrics }>('/evolution/dashboard'),
  scanProposals: () =>
    isTauri()
      ? apiInvoke<{ proposals: RuleProposal[]; count: number }>('scan_rule_proposals')
      : get<{ proposals: RuleProposal[]; count: number }>('/evolution/rule-proposals'),
  promoteRule: (memoryKey: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; memory_key: string; rule_text: string }>('promote_rule', {
          memory_key: memoryKey,
        })
      : post<{ success: boolean; memory_key: string; rule_text: string }>(
          '/evolution/rule-proposals/promote',
          { memory_key: memoryKey }
        ),
  scanSkillCandidates: () =>
    isTauri()
      ? apiInvoke<{ candidates: SkillCandidateInfo[]; count: number }>('scan_skill_candidates')
      : get<{ candidates: SkillCandidateInfo[]; count: number }>('/evolution/skill-candidates'),
  generateSkillDraft: (name: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; name: string; path: string }>('generate_skill_draft', {
          name,
        })
      : post<{ success: boolean; name: string; path: string }>(
          '/evolution/skill-candidates/draft',
          { name }
        ),
  activateSkillDraft: (name: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; name: string; path: string }>('activate_skill_draft', {
          name,
        })
      : post<{ success: boolean; name: string; path: string }>(
          '/evolution/skill-candidates/activate',
          { name }
        ),
};

// ── Provider API ──────────────────────────────────────────────────────────

export const providerApi = {
  listTemplates: () =>
    isTauri()
      ? apiInvoke<{ providers: ProviderTemplate[] }>('list_model_templates')
      : get<{ providers: ProviderTemplate[] }>('/models/templates'),
  listConfigured: () =>
    isTauri()
      ? apiInvoke<ConfiguredModelListResponse>('list_configured_models')
      : get<ConfiguredModelListResponse>('/models/configured'),
  setDefault: (modelId: string) =>
    isTauri()
      ? apiInvoke<{
          success: boolean;
          model_id: string;
          display_name: string;
          model: string;
          provider: string;
        }>('set_default_model', { modelId })
      : post<{
          success: boolean;
          model_id: string;
          display_name: string;
          model: string;
          provider: string;
        }>('/models/default', { model_id: modelId }),
  upsertConfigured: (req: {
    id?: string;
    display_name?: string;
    provider: string;
    model: string;
    api_key?: string;
    base_url?: string;
    temperature?: number;
    max_tokens?: number;
    context_window?: number | null;
    enabled?: boolean;
    set_default?: boolean;
    /** 思考深度:`auto`/`disabled`/`minimal`/`low`/`medium`/`high`/`<number>` */
    thinking?: string;
  }) =>
    isTauri()
      ? apiInvoke<{
          success: boolean;
          model_id: string;
          auth_source?: string;
        }>('upsert_configured_model', { req })
      : post<{
          success: boolean;
          model_id: string;
          auth_source?: string;
        }>('/models/configured', req),
  deleteConfigured: (modelId: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('delete_configured_model', { modelId })
      : del<{ success: boolean }>(`/models/configured/${encodeURIComponent(modelId)}`),
  test: (req: { provider: string; model: string; api_key?: string; base_url?: string }) =>
    isTauri()
      ? apiInvoke<TestConnectionResponse>('test_connection', {
          provider: req.provider,
          model: req.model,
          apiKey: req.api_key,
          baseUrl: req.base_url,
        })
      : post<TestConnectionResponse>('/providers/test', req),
  /** Query whether a (provider, model) supports a thinking-depth control.
   *  Used to show/hide the 思考深度 dropdown. */
  getThinkingSupport: (req: { provider: string; model: string }) =>
    isTauri()
      ? apiInvoke<{
          supports: boolean;
          protocol: string;
          levels: string[];
          model: string;
          provider: string;
        }>('get_thinking_support', {
          provider: req.provider,
          model: req.model,
        })
      : get<{
          supports: boolean;
          protocol: string;
          levels: string[];
          model: string;
          provider: string;
        }>(
          `/models/thinking-support?provider=${encodeURIComponent(req.provider)}&model=${encodeURIComponent(req.model)}`
        ),
  /** Dynamically set the active agent's thinking-depth at runtime. Decoupled
   *  from model config — the user toggles it from the chat input toolbar.
   *  Models that don't support thinking silently ignore it. */
  setThinking: (spec: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; spec: string; applied: boolean }>('set_thinking', { spec })
      : post<{ success: boolean; spec: string; applied: boolean }>('/models/thinking', { spec }),
};

// ── Plugin API ──────────────────────────────────────────────────────────

export interface PluginInfo {
  name: string;
  display_name: string;
  version: string;
  description: string;
  author: string | null;
  license: string | null;
  scope: string;
  enabled: boolean;
  path: string;
  capabilities: string[];
  keywords: string[];
  dependencies: { name: string; version: string | null }[];
  config: Record<string, PluginConfigEntry>;
  config_values: Record<string, unknown>;
}

export interface PluginConfigEntry {
  type: 'string' | 'number' | 'boolean' | 'directory' | 'file';
  title: string;
  description: string;
  sensitive: boolean;
  required: boolean;
  default: unknown | null;
  multiple: boolean;
  min: number | null;
  max: number | null;
}

export interface PluginMutationResult {
  success: boolean;
  message?: string;
  error?: string;
  wiring_ok?: boolean;
  errors?: string[];
}

export interface PluginValidationReport {
  valid: boolean;
  name: string | null;
  components: string[];
  errors: string[];
}

export interface PluginThemeDefinition {
  name: string;
  display_name: string | null;
  dark: boolean;
  colors: Record<string, string>;
  plugin: string;
}

export interface PluginThemesResult {
  themes: PluginThemeDefinition[];
  active: string | null;
}

export interface PluginOutputStyle {
  name: string;
  description: string;
  instructions: string;
  plugin: string;
}

export interface PluginOutputStylesResult {
  styles: PluginOutputStyle[];
  active: string | null;
}

export const pluginApi = {
  list: () => (isTauri() ? apiInvoke<PluginInfo[]>('list_plugins') : get<PluginInfo[]>('/plugins')),
  get: (name: string) =>
    isTauri()
      ? apiInvoke<{ info: PluginInfo; resolved?: Record<string, any> }>('get_plugin', { name })
      : get<{ info: PluginInfo; resolved?: Record<string, any> }>(`/plugins/${name}`),
  install: (req: { source: string; scope?: string }) =>
    isTauri()
      ? apiInvoke<PluginMutationResult & { plugin_id?: string; info?: PluginInfo }>(
          'install_plugin',
          { source: req.source, scope: req.scope }
        )
      : post<PluginMutationResult & { plugin_id?: string; info?: PluginInfo }>(
          '/plugins/install',
          req
        ),
  uninstall: (req: { name: string; keep_data?: boolean }) =>
    isTauri()
      ? apiInvoke<PluginMutationResult>('uninstall_plugin', {
          name: req.name,
          keep_data: req.keep_data,
        })
      : post<PluginMutationResult>('/plugins/uninstall', req),
  enable: (name: string) =>
    isTauri()
      ? apiInvoke<PluginMutationResult>('enable_plugin', { name })
      : post<PluginMutationResult>(`/plugins/${name}/enable`),
  disable: (name: string) =>
    isTauri()
      ? apiInvoke<PluginMutationResult>('disable_plugin', {
          name,
        })
      : post<PluginMutationResult>(`/plugins/${name}/disable`),
  configure: (name: string, values: Record<string, unknown>) =>
    isTauri()
      ? apiInvoke<PluginMutationResult>('configure_plugin', { name, values })
      : post<PluginMutationResult>(`/plugins/${name}/config`, { values }),
  reload: () =>
    isTauri()
      ? apiInvoke<{
          success: boolean;
          total?: number;
          enabled?: number;
          skills_loaded?: number;
          hooks_registered?: number;
          mcp_connected?: number;
          agents_loaded?: number;
          lsp_languages_loaded?: number;
          monitors_loaded?: number;
          themes_loaded?: number;
          output_styles_loaded?: number;
          errors?: string[];
          message?: string;
          error?: string;
        }>('reload_plugins')
      : post<{
          success: boolean;
          total?: number;
          enabled?: number;
          skills_loaded?: number;
          hooks_registered?: number;
          mcp_connected?: number;
          agents_loaded?: number;
          lsp_languages_loaded?: number;
          monitors_loaded?: number;
          themes_loaded?: number;
          output_styles_loaded?: number;
          errors?: string[];
          message?: string;
          error?: string;
        }>('/plugins/reload'),
  scaffold: (directory: string, name: string) =>
    isTauri()
      ? apiInvoke<PluginMutationResult & { path?: string; name?: string }>('scaffold_plugin', {
          directory,
          name,
        })
      : post<PluginMutationResult & { path?: string; name?: string }>('/plugins/scaffold', {
          directory,
          name,
        }),
  validate: (directory: string) =>
    isTauri()
      ? apiInvoke<PluginValidationReport>('validate_plugin', { directory })
      : post<PluginValidationReport>('/plugins/validate', { directory }),
  themes: () =>
    isTauri()
      ? apiInvoke<PluginThemesResult>('list_plugin_themes')
      : get<PluginThemesResult>('/plugins/themes'),
  activateTheme: (name: string | null) =>
    isTauri()
      ? apiInvoke<{ success: boolean; active: string | null; theme: PluginThemeDefinition | null }>(
          'activate_plugin_theme',
          { name }
        )
      : post<{ success: boolean; active: string | null; theme: PluginThemeDefinition | null }>(
          '/plugins/theme',
          { name }
        ),
  outputStyles: () =>
    isTauri()
      ? apiInvoke<PluginOutputStylesResult>('list_plugin_output_styles')
      : get<PluginOutputStylesResult>('/plugins/output-styles'),
  activateOutputStyle: (name: string | null) =>
    isTauri()
      ? apiInvoke<{ success: boolean; active: string | null }>('activate_plugin_output_style', {
          name,
        })
      : post<{ success: boolean; active: string | null }>('/plugins/output-style', { name }),
};

// ── Hooks API ──────────────────────────────────────────────────────────

/** A registered hook source and its rule count, mirroring the backend
 *  `HookRegistry::list_sources` result. Sources look like `user_config`,
 *  `skill:foo`, or `plugin:bar`. */
export interface HookSourceInfo {
  source: string;
  rule_count: number;
}

/** Summary returned by a hooks reload: how many rules were merged and where
 *  they came from. */
export interface HooksReloadSummary {
  success: boolean;
  rule_count: number;
  loaded_from: string[];
  message: string;
}

export interface HookTestResult {
  event: string;
  matcher: string;
  matches: { source: string; matcher: string; action: string }[];
}

export const hooksApi = {
  list: () =>
    isTauri() ? apiInvoke<HookSourceInfo[]>('list_hooks') : get<HookSourceInfo[]>('/hooks'),
  reload: () =>
    isTauri()
      ? apiInvoke<HooksReloadSummary>('reload_hooks')
      : post<HooksReloadSummary>('/hooks/reload'),
  events: () =>
    isTauri() ? apiInvoke<string[]>('list_hook_events') : get<string[]>('/hooks/events'),
  test: (event: string, matcher?: string) =>
    isTauri()
      ? apiInvoke<HookTestResult>('test_hook', { event, matcher })
      : post<HookTestResult>('/hooks/test', { event, matcher }),
};

// ── Scheduler API (定时任务) ──────────────────────────────────────

export interface SchedulerTask {
  id: string;
  name: string;
  cron_expr: string;
  prompt: string;
  status: string;
  last_run_at: string | null;
  last_result: string | null;
  created_at: string;
  next_run: string | null;
}

export const schedulerApi = {
  list: () =>
    isTauri()
      ? apiInvoke<SchedulerTask[]>('list_scheduler_tasks')
      : get<SchedulerTask[]>('/scheduler/tasks'),
  create: (data: { name: string; cron_expr: string; prompt: string }) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('add_scheduler_task', {
          name: data.name,
          cron_expr: data.cron_expr,
          prompt: data.prompt,
        })
      : post<{ success: boolean }>('/scheduler/tasks', data),
  updateStatus: (id: string, enabled: boolean) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('set_scheduler_task_status', {
          id,
          status: enabled ? 'enabled' : 'disabled',
        })
      : put<{ success: boolean }>(`/scheduler/tasks/${id}/status`, {
          status: enabled ? 'enabled' : 'disabled',
        }),
  run: (id: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; result?: string; error?: string }>('run_scheduler_task', {
          id,
        })
      : post<{ success: boolean; result?: string; error?: string }>(`/scheduler/tasks/${id}/run`),
  delete: (id: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('remove_scheduler_task', { id })
      : del<{ success: boolean }>(`/scheduler/tasks/${id}`),
};

// ── Auto Memory API (自动记忆) ───────────────────────────────────

// ── Worktree API (Git 工作树) ─────────────────────────────────────

export interface WorktreeInfo {
  path: string;
  branch: string;
  managed: boolean;
  head: string;
}

export interface UnattendedWorktreeInfo {
  run_id: string;
  branch: string;
  path: string | null;
  head: string;
  status: string;
  active: boolean;
  locked: boolean;
  lock_reason: string | null;
  uncommitted_changes: boolean;
  ahead_commits: number;
  has_changes: boolean;
  orphan_branch: boolean;
}

export interface UnattendedWorktreeCleanupResult {
  removed: string[];
  unlocked: string[];
  kept: string[];
  errors: string[];
}

export interface UnattendedWorktreeMergeResult {
  success: boolean;
  run_id: string;
  status: 'merged' | 'no_changes' | 'already_integrated';
  branch: string;
  changed_files: string[];
  merge_commit: string | null;
  cleanup_warning: string | null;
}

export const worktreeApi = {
  list: () =>
    isTauri() ? apiInvoke<WorktreeInfo[]>('list_worktrees') : get<WorktreeInfo[]>('/worktrees'),
  create: (req: { branch: string; base?: string; path?: string }) =>
    isTauri()
      ? apiInvoke<WorktreeInfo>('create_worktree', {
          branch: req.branch,
          base: req.base,
          path: req.path,
        })
      : post<WorktreeInfo>('/worktrees', req),
  remove: (path: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean }>('remove_worktree', { path })
      : del<{ success: boolean }>(`/worktrees?path=${encodeURIComponent(path)}`),
  listUnattended: () =>
    isTauri()
      ? apiInvoke<UnattendedWorktreeInfo[]>('list_unattended_worktrees')
      : get<UnattendedWorktreeInfo[]>('/worktrees/unattended'),
  mergeUnattended: (runId: string) =>
    isTauri()
      ? apiInvoke<UnattendedWorktreeMergeResult>('merge_unattended_worktree', { runId })
      : post<UnattendedWorktreeMergeResult>(`/worktrees/unattended/${runId}/merge`, {}),
  discardUnattended: (runId: string) =>
    isTauri()
      ? apiInvoke<{ success: boolean; discarded: string }>('discard_unattended_worktree', {
          runId,
        })
      : del<{ success: boolean; discarded: string }>(`/worktrees/unattended/${runId}`),
  cleanupUnattended: () =>
    isTauri()
      ? apiInvoke<UnattendedWorktreeCleanupResult>('cleanup_unattended_worktrees')
      : post<UnattendedWorktreeCleanupResult>('/worktrees/unattended/cleanup', {}),
};
