// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a human is present during a run. Unattended runs apply the
 * configured write preflight and fail task errors without waiting for input;
 * both modes can still be explicitly paused through the shared control path.
 */
export type AttendedMode = "attended" | "unattended";
