// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a human is present during a run. Drives safety-gate behaviour:
 * unattended runs skip the approval gate (when the plan passes preflight),
 * reject writes at pre-scan, and never pause for human intervention.
 */
export type AttendedMode = "attended" | "unattended";
