// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single event in the unified conversation timeline.
 *
 * The frontend subscribes to `conversation://event` and appends each event
 * to a unified timeline that replaces the dual chat / TaskRuntimeMainPanel
 * rendering.
 */
export type ConversationRuntimeEvent = { "type": "route_decision", route: string, confidence: number, reason: string, matched_feedback_pattern: string | null, suggested_workers: Array<string>, interaction_mode: string, } | { "type": "initial_thinking", worker_id: string | null, } | { "type": "worker_started", worker_id: string, agent_role: string, title: string, task_description: string, } | { "type": "worker_tool_call", worker_id: string, tool_name: string, tool_args: JsonValue, success: boolean | null, } | { "type": "worker_result", worker_id: string, summary: string, files_changed: Array<string>, } | { "type": "llm_usage", model: string, input_tokens: bigint, output_tokens: bigint, cached_input_tokens: bigint, cache_creation_input_tokens: bigint, usage_reported: boolean, worker_id: string | null, } | { "type": "final_answer", content: string, usage_summary: JsonValue | null, } | { "type": "approval_request", request_id: string, tool_name: string, prompt: string, } | { "type": "error", stage: string, message: string, worker_id: string | null, };
