// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Manual override of how a user message should be handled (plan §582-586).
 * `Auto` defers to the heuristic classifier; the other two force a path.
 */
export type InteractionMode = "chat" | "plan" | "auto";
