// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainProfile } from "./DomainProfile";
import type { PlanTaskKind } from "./PlanTaskKind";
import type { TodoStatus } from "./TodoStatus";

/**
 * One node in the plan DAG. `depends_on` is the canonical edge list; the
 * scheduler (PR 3) builds adjacency indexes from it but `PlanTask` remains
 * the serialized node.
 */
export type PlanTask = { id: string, title: string, description: string, kind: PlanTaskKind, agent_role: string, domain_profile: DomainProfile, depends_on: Array<string>, parallel_group: string | null, files: Array<string>, allowed_tools: Array<string>, verification: Array<string>, retry_count: number, max_retries: number, failure_fingerprint: string | null, status: TodoStatus, 
/**
 * Stable sort key for display ordering. Set by plan generation (sequential
 * index) and updated by `reorder_tasks`. Separated from `parallel_group`
 * (which encodes parallel-fanout grouping, not display order) to avoid
 * semantic pollution.
 */
sort_order: bigint, };
