// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionInfo = { session_id: string | null, message_count: number, tool_count: number, skill_count: number, mcp_server_count: number, };
