// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 统一的流式事件（SSE 和 WebSocket 共用）
 */
export type StreamingEvent = { "event": "token", data: string, } | { "event": "tool_start", name: string, args: JsonValue, } | { "event": "tool_result", name: string, result: string, success: boolean, } | { "event": "final_answer", data: string, } | { "event": "error", message: string, } | { "event": "approval_request", request_id: string, tool_name: string, args: JsonValue, prompt: string, } | { "event": "input_request", request_id: string, prompt: string, } | { "event": "chart", spec: JsonValue, } | { "event": "cancelled" } | { "event": "thinking_start" } | { "event": "thinking_end", prompt_tokens: number, completion_tokens: number, } | { "event": "tool_batch_start", tool_count: number, } | { "event": "tool_batch_end" } | { "event": "done" };
