// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime path persisted on a run.
 */
export type TaskRouteKind = "complex_runtime" | "parallel_readonly_delegation";
