// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubagentTaskResult } from "./SubagentTaskResult";
import type { SuggestedTask } from "./SuggestedTask";

/**
 * Compact per-task summary produced at every task boundary. Downstream
 * subagents consume this instead of the full raw conversation — see the
 * "Summary Chain" section of the plan.
 */
export type TaskExecutionSummary = {
  run_id: string;
  task_id: string;
  subagent_name: string;
  result: SubagentTaskResult;
  decisions: Array<string>;
  next_implications: Array<string>;
  suggested_tasks: Array<SuggestedTask>;
  created_at: string;
};
