// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status of a [`TaskRun`]. The GUI must render from these states
 * and `RuntimeTaskEvent`s, never from local guesses.
 *
 * Allowed transitions (see [`TaskRunStatus::can_transition_to`]):
 *
 * ```text
 * Pending → Running → Completed
 *              │  ↘
 *           Paused  Failed → Running (retry)
 *              │
 *           Cancelled
 * ```
 *
 * 极简 6 态(对齐 Claude Code/Codex:plan 审批不进状态机,用 Paused 表达)。
 * 删去了 Planning/AwaitingPlanApproval/Ready/WaitingApproval/WaitingInput/Suspended/Cancelling
 * —— 这些"plan 是否被批准"的语义改由编排层(L1) + Paused 承载,不进 run 状态机。
 */
export type TaskRunStatus = "pending" | "running" | "paused" | "cancelled" | "failed" | "completed";
