// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status of a [`TaskRun`]. The GUI must render from these states
 * and `RuntimeTaskEvent`s, never from local guesses.
 *
 * Allowed transitions (see [`TaskRunStatus::can_transition_to`]):
 * ```text
 * Pending -> Planning
 * Planning -> AwaitingPlanApproval
 * AwaitingPlanApproval -> Ready | Cancelled
 * Ready -> Running
 * Running -> WaitingApproval | WaitingInput | Suspended | Paused | Cancelling | Failed | Completed
 * WaitingApproval -> Running | Suspended | Cancelled
 * WaitingInput -> Running | Suspended | Cancelled
 * Suspended -> Ready | Cancelled
 * Paused -> Running | AwaitingPlanApproval | Cancelled
 * Cancelling -> Cancelled | Failed
 * Failed -> Ready | Cancelled  (Ready: reserved for future retry-from-failed)
 * ```
 */
export type TaskRunStatus = "pending" | "planning" | "awaiting_plan_approval" | "ready" | "running" | "waiting_approval" | "waiting_input" | "suspended" | "paused" | "cancelling" | "cancelled" | "failed" | "completed";
