// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttendedMode } from "./AttendedMode";
import type { DomainProfile } from "./DomainProfile";
import type { TaskRunStatus } from "./TaskRunStatus";

/**
 * A single complex-task run. One run = one user goal that goes through the
 * plan → approve → execute → review → synthesize lifecycle.
 */
export type TaskRun = { run_id: string, workspace_id: string, conversation_id: string, root_message_id: string, domain_profile: DomainProfile, status: TaskRunStatus, goal: string, plan_id: string | null, route: string, 
/**
 * Whether a human is present (Attended) or this is a cron/IM trigger
 * (Unattended). Drives safety-gate behaviour in plan_execute /
 * executor.  Default: Attended (chat behaviours unchanged).
 */
attended_mode: AttendedMode, created_at: string, updated_at: string, };
