// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentUpdate } from "./AgentUpdate";
import type { ChannelsUpdate } from "./ChannelsUpdate";
import type { LoggingUpdate } from "./LoggingUpdate";
import type { McpUpdate } from "./McpUpdate";
import type { ModelUpdate } from "./ModelUpdate";
import type { ServerUpdate } from "./ServerUpdate";

/**
 * PUT /api/config/full — 完整配置更新
 */
export type UpdateFullConfigRequest = { model: ModelUpdate | null, agent: AgentUpdate | null, mcp: McpUpdate | null, channels: ChannelsUpdate | null, server: ServerUpdate | null, logging: LoggingUpdate | null, };
