// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single LLM usage record persisted to SQLite for trend analysis.
 */
export type UsageRecord = { id: string, session_id: string, run_id: string | null, worker_id: string | null, model: string, provider: string | null, route_kind: string | null, input_tokens: bigint, output_tokens: bigint, cached_input_tokens: bigint, cache_creation_input_tokens: bigint, usage_reported: boolean, system_prompt_hash: string | null, tools_schema_hash: string | null, cwd_hash: string | null, worker_prompt_hash: string | null, created_at: string, };
