// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { WorkerTraceEventKind } from "./WorkerTraceEventKind";

/**
 * A realtime event scoped to a top-level run and, optionally, a child worker.
 */
export type WorkerTraceEvent = { event_id: string, run_id: string, worker_id: string | null, parent_worker_id: string | null, agent_name: string | null, title: string | null, task: string | null, event_type: WorkerTraceEventKind, payload: JsonValue, timestamp: string, };
