// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Realtime trace events for GUI-visible run/worker execution.
 *
 * `RuntimeTaskEvent` is the persisted TaskRuntime ledger. This type is the
 * lightweight realtime protocol used by Chat, TaskRuntime, Auto routing, and
 * subagents so the frontend can render one coherent "run with workers" view.
 */
export type WorkerTraceEventKind = "run_started" | "run_status_changed" | "run_completed" | "run_failed" | "run_cancelled" | "worker_planned" | "worker_started" | "worker_thinking_start" | "worker_thinking_delta" | "worker_thinking_end" | "worker_tool_start" | "worker_tool_result" | "worker_token_delta" | "worker_artifact" | "worker_completed" | "worker_failed" | "worker_cancelled" | "approval_requested" | "approval_resolved" | "note";
